package cn.xjtu.zun.tiesheyuan.pojo;

public class DataClassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_classification.ID
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_classification.SJLXFW
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    private String sjlxfw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_classification.JTSJLX
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    private String jtsjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_classification.database
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    private String database;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_classification.ID
     *
     * @return the value of data_classification.ID
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_classification.ID
     *
     * @param id the value for data_classification.ID
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_classification.SJLXFW
     *
     * @return the value of data_classification.SJLXFW
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public String getSjlxfw() {
        return sjlxfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_classification.SJLXFW
     *
     * @param sjlxfw the value for data_classification.SJLXFW
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public void setSjlxfw(String sjlxfw) {
        this.sjlxfw = sjlxfw == null ? null : sjlxfw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_classification.JTSJLX
     *
     * @return the value of data_classification.JTSJLX
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public String getJtsjlx() {
        return jtsjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_classification.JTSJLX
     *
     * @param jtsjlx the value for data_classification.JTSJLX
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public void setJtsjlx(String jtsjlx) {
        this.jtsjlx = jtsjlx == null ? null : jtsjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_classification.database
     *
     * @return the value of data_classification.database
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public String getDatabase() {
        return database;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_classification.database
     *
     * @param database the value for data_classification.database
     *
     * @mbg.generated Thu Aug 03 17:47:06 CST 2023
     */
    public void setDatabase(String database) {
        this.database = database == null ? null : database.trim();
    }
}