package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class DizhidiaohuiDizhigouzaoDuanceng {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZ_DCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long dzdhDzgzDcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long dzdhDzgzid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.HDXFL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String hdxfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DCXZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String dcxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DCCZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String dccz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DLKD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal dlkd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DCCD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal dccd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.DDWZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String ddwz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.HDSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String hdsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.HDXZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String hdxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.HDSL_SP
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal hdslSp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.HDSL_CZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal hdslCz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_dizhigouzao_duanceng.ZDWCL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zdwcl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZ_DCID
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZ_DCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getDzdhDzgzDcid() {
        return dzdhDzgzDcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZ_DCID
     *
     * @param dzdhDzgzDcid the value for dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZ_DCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDzdhDzgzDcid(Long dzdhDzgzDcid) {
        this.dzdhDzgzDcid = dzdhDzgzDcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZID
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getDzdhDzgzid() {
        return dzdhDzgzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZID
     *
     * @param dzdhDzgzid the value for dizhidiaohui_dizhigouzao_duanceng.DZDH_DZGZID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDzdhDzgzid(Long dzdhDzgzid) {
        this.dzdhDzgzid = dzdhDzgzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDXFL
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.HDXFL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getHdxfl() {
        return hdxfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDXFL
     *
     * @param hdxfl the value for dizhidiaohui_dizhigouzao_duanceng.HDXFL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHdxfl(String hdxfl) {
        this.hdxfl = hdxfl == null ? null : hdxfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DCXZ
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DCXZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getDcxz() {
        return dcxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DCXZ
     *
     * @param dcxz the value for dizhidiaohui_dizhigouzao_duanceng.DCXZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDcxz(String dcxz) {
        this.dcxz = dcxz == null ? null : dcxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DCCZ
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DCCZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getDccz() {
        return dccz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DCCZ
     *
     * @param dccz the value for dizhidiaohui_dizhigouzao_duanceng.DCCZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDccz(String dccz) {
        this.dccz = dccz == null ? null : dccz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DLKD
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DLKD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getDlkd() {
        return dlkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DLKD
     *
     * @param dlkd the value for dizhidiaohui_dizhigouzao_duanceng.DLKD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDlkd(BigDecimal dlkd) {
        this.dlkd = dlkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DCCD
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DCCD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getDccd() {
        return dccd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DCCD
     *
     * @param dccd the value for dizhidiaohui_dizhigouzao_duanceng.DCCD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDccd(BigDecimal dccd) {
        this.dccd = dccd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.DDWZ
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.DDWZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getDdwz() {
        return ddwz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.DDWZ
     *
     * @param ddwz the value for dizhidiaohui_dizhigouzao_duanceng.DDWZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDdwz(String ddwz) {
        this.ddwz = ddwz == null ? null : ddwz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDSD
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.HDSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getHdsd() {
        return hdsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDSD
     *
     * @param hdsd the value for dizhidiaohui_dizhigouzao_duanceng.HDSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHdsd(String hdsd) {
        this.hdsd = hdsd == null ? null : hdsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDXZ
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.HDXZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getHdxz() {
        return hdxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDXZ
     *
     * @param hdxz the value for dizhidiaohui_dizhigouzao_duanceng.HDXZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHdxz(String hdxz) {
        this.hdxz = hdxz == null ? null : hdxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDSL_SP
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.HDSL_SP
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getHdslSp() {
        return hdslSp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDSL_SP
     *
     * @param hdslSp the value for dizhidiaohui_dizhigouzao_duanceng.HDSL_SP
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHdslSp(BigDecimal hdslSp) {
        this.hdslSp = hdslSp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDSL_CZ
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.HDSL_CZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getHdslCz() {
        return hdslCz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.HDSL_CZ
     *
     * @param hdslCz the value for dizhidiaohui_dizhigouzao_duanceng.HDSL_CZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHdslCz(BigDecimal hdslCz) {
        this.hdslCz = hdslCz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_dizhigouzao_duanceng.ZDWCL
     *
     * @return the value of dizhidiaohui_dizhigouzao_duanceng.ZDWCL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZdwcl() {
        return zdwcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_dizhigouzao_duanceng.ZDWCL
     *
     * @param zdwcl the value for dizhidiaohui_dizhigouzao_duanceng.ZDWCL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZdwcl(BigDecimal zdwcl) {
        this.zdwcl = zdwcl;
    }
}