package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DizhidiaohuiBuliangdizhiHuapoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public DizhidiaohuiBuliangdizhiHuapoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDzdhBldzHpidIsNull() {
            addCriterion("DZDH_BLDZ_HPID is null");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidIsNotNull() {
            addCriterion("DZDH_BLDZ_HPID is not null");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidEqualTo(Long value) {
            addCriterion("DZDH_BLDZ_HPID =", value, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidNotEqualTo(Long value) {
            addCriterion("DZDH_BLDZ_HPID <>", value, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidGreaterThan(Long value) {
            addCriterion("DZDH_BLDZ_HPID >", value, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidGreaterThanOrEqualTo(Long value) {
            addCriterion("DZDH_BLDZ_HPID >=", value, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidLessThan(Long value) {
            addCriterion("DZDH_BLDZ_HPID <", value, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidLessThanOrEqualTo(Long value) {
            addCriterion("DZDH_BLDZ_HPID <=", value, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidIn(List<Long> values) {
            addCriterion("DZDH_BLDZ_HPID in", values, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidNotIn(List<Long> values) {
            addCriterion("DZDH_BLDZ_HPID not in", values, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidBetween(Long value1, Long value2) {
            addCriterion("DZDH_BLDZ_HPID between", value1, value2, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzHpidNotBetween(Long value1, Long value2) {
            addCriterion("DZDH_BLDZ_HPID not between", value1, value2, "dzdhBldzHpid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidIsNull() {
            addCriterion("DZDH_BLDZID is null");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidIsNotNull() {
            addCriterion("DZDH_BLDZID is not null");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidEqualTo(Long value) {
            addCriterion("DZDH_BLDZID =", value, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidNotEqualTo(Long value) {
            addCriterion("DZDH_BLDZID <>", value, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidGreaterThan(Long value) {
            addCriterion("DZDH_BLDZID >", value, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidGreaterThanOrEqualTo(Long value) {
            addCriterion("DZDH_BLDZID >=", value, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidLessThan(Long value) {
            addCriterion("DZDH_BLDZID <", value, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidLessThanOrEqualTo(Long value) {
            addCriterion("DZDH_BLDZID <=", value, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidIn(List<Long> values) {
            addCriterion("DZDH_BLDZID in", values, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidNotIn(List<Long> values) {
            addCriterion("DZDH_BLDZID not in", values, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidBetween(Long value1, Long value2) {
            addCriterion("DZDH_BLDZID between", value1, value2, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andDzdhBldzidNotBetween(Long value1, Long value2) {
            addCriterion("DZDH_BLDZID not between", value1, value2, "dzdhBldzid");
            return (Criteria) this;
        }

        public Criteria andHtwzIsNull() {
            addCriterion("HTWZ is null");
            return (Criteria) this;
        }

        public Criteria andHtwzIsNotNull() {
            addCriterion("HTWZ is not null");
            return (Criteria) this;
        }

        public Criteria andHtwzEqualTo(String value) {
            addCriterion("HTWZ =", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzNotEqualTo(String value) {
            addCriterion("HTWZ <>", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzGreaterThan(String value) {
            addCriterion("HTWZ >", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzGreaterThanOrEqualTo(String value) {
            addCriterion("HTWZ >=", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzLessThan(String value) {
            addCriterion("HTWZ <", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzLessThanOrEqualTo(String value) {
            addCriterion("HTWZ <=", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzLike(String value) {
            addCriterion("HTWZ like", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzNotLike(String value) {
            addCriterion("HTWZ not like", value, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzIn(List<String> values) {
            addCriterion("HTWZ in", values, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzNotIn(List<String> values) {
            addCriterion("HTWZ not in", values, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzBetween(String value1, String value2) {
            addCriterion("HTWZ between", value1, value2, "htwz");
            return (Criteria) this;
        }

        public Criteria andHtwzNotBetween(String value1, String value2) {
            addCriterion("HTWZ not between", value1, value2, "htwz");
            return (Criteria) this;
        }

        public Criteria andLxTjIsNull() {
            addCriterion("LX_TJ is null");
            return (Criteria) this;
        }

        public Criteria andLxTjIsNotNull() {
            addCriterion("LX_TJ is not null");
            return (Criteria) this;
        }

        public Criteria andLxTjEqualTo(String value) {
            addCriterion("LX_TJ =", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjNotEqualTo(String value) {
            addCriterion("LX_TJ <>", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjGreaterThan(String value) {
            addCriterion("LX_TJ >", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjGreaterThanOrEqualTo(String value) {
            addCriterion("LX_TJ >=", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjLessThan(String value) {
            addCriterion("LX_TJ <", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjLessThanOrEqualTo(String value) {
            addCriterion("LX_TJ <=", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjLike(String value) {
            addCriterion("LX_TJ like", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjNotLike(String value) {
            addCriterion("LX_TJ not like", value, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjIn(List<String> values) {
            addCriterion("LX_TJ in", values, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjNotIn(List<String> values) {
            addCriterion("LX_TJ not in", values, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjBetween(String value1, String value2) {
            addCriterion("LX_TJ between", value1, value2, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxTjNotBetween(String value1, String value2) {
            addCriterion("LX_TJ not between", value1, value2, "lxTj");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdIsNull() {
            addCriterion("LX_HDMSD is null");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdIsNotNull() {
            addCriterion("LX_HDMSD is not null");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdEqualTo(String value) {
            addCriterion("LX_HDMSD =", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdNotEqualTo(String value) {
            addCriterion("LX_HDMSD <>", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdGreaterThan(String value) {
            addCriterion("LX_HDMSD >", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdGreaterThanOrEqualTo(String value) {
            addCriterion("LX_HDMSD >=", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdLessThan(String value) {
            addCriterion("LX_HDMSD <", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdLessThanOrEqualTo(String value) {
            addCriterion("LX_HDMSD <=", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdLike(String value) {
            addCriterion("LX_HDMSD like", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdNotLike(String value) {
            addCriterion("LX_HDMSD not like", value, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdIn(List<String> values) {
            addCriterion("LX_HDMSD in", values, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdNotIn(List<String> values) {
            addCriterion("LX_HDMSD not in", values, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdBetween(String value1, String value2) {
            addCriterion("LX_HDMSD between", value1, value2, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHdmsdNotBetween(String value1, String value2) {
            addCriterion("LX_HDMSD not between", value1, value2, "lxHdmsd");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxIsNull() {
            addCriterion("LX_HMYCMGX is null");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxIsNotNull() {
            addCriterion("LX_HMYCMGX is not null");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxEqualTo(String value) {
            addCriterion("LX_HMYCMGX =", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxNotEqualTo(String value) {
            addCriterion("LX_HMYCMGX <>", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxGreaterThan(String value) {
            addCriterion("LX_HMYCMGX >", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxGreaterThanOrEqualTo(String value) {
            addCriterion("LX_HMYCMGX >=", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxLessThan(String value) {
            addCriterion("LX_HMYCMGX <", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxLessThanOrEqualTo(String value) {
            addCriterion("LX_HMYCMGX <=", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxLike(String value) {
            addCriterion("LX_HMYCMGX like", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxNotLike(String value) {
            addCriterion("LX_HMYCMGX not like", value, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxIn(List<String> values) {
            addCriterion("LX_HMYCMGX in", values, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxNotIn(List<String> values) {
            addCriterion("LX_HMYCMGX not in", values, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxBetween(String value1, String value2) {
            addCriterion("LX_HMYCMGX between", value1, value2, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHmycmgxNotBetween(String value1, String value2) {
            addCriterion("LX_HMYCMGX not between", value1, value2, "lxHmycmgx");
            return (Criteria) this;
        }

        public Criteria andLxHdfsIsNull() {
            addCriterion("LX_HDFS is null");
            return (Criteria) this;
        }

        public Criteria andLxHdfsIsNotNull() {
            addCriterion("LX_HDFS is not null");
            return (Criteria) this;
        }

        public Criteria andLxHdfsEqualTo(String value) {
            addCriterion("LX_HDFS =", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsNotEqualTo(String value) {
            addCriterion("LX_HDFS <>", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsGreaterThan(String value) {
            addCriterion("LX_HDFS >", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsGreaterThanOrEqualTo(String value) {
            addCriterion("LX_HDFS >=", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsLessThan(String value) {
            addCriterion("LX_HDFS <", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsLessThanOrEqualTo(String value) {
            addCriterion("LX_HDFS <=", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsLike(String value) {
            addCriterion("LX_HDFS like", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsNotLike(String value) {
            addCriterion("LX_HDFS not like", value, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsIn(List<String> values) {
            addCriterion("LX_HDFS in", values, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsNotIn(List<String> values) {
            addCriterion("LX_HDFS not in", values, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsBetween(String value1, String value2) {
            addCriterion("LX_HDFS between", value1, value2, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andLxHdfsNotBetween(String value1, String value2) {
            addCriterion("LX_HDFS not between", value1, value2, "lxHdfs");
            return (Criteria) this;
        }

        public Criteria andWdztIsNull() {
            addCriterion("WDZT is null");
            return (Criteria) this;
        }

        public Criteria andWdztIsNotNull() {
            addCriterion("WDZT is not null");
            return (Criteria) this;
        }

        public Criteria andWdztEqualTo(String value) {
            addCriterion("WDZT =", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztNotEqualTo(String value) {
            addCriterion("WDZT <>", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztGreaterThan(String value) {
            addCriterion("WDZT >", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztGreaterThanOrEqualTo(String value) {
            addCriterion("WDZT >=", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztLessThan(String value) {
            addCriterion("WDZT <", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztLessThanOrEqualTo(String value) {
            addCriterion("WDZT <=", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztLike(String value) {
            addCriterion("WDZT like", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztNotLike(String value) {
            addCriterion("WDZT not like", value, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztIn(List<String> values) {
            addCriterion("WDZT in", values, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztNotIn(List<String> values) {
            addCriterion("WDZT not in", values, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztBetween(String value1, String value2) {
            addCriterion("WDZT between", value1, value2, "wdzt");
            return (Criteria) this;
        }

        public Criteria andWdztNotBetween(String value1, String value2) {
            addCriterion("WDZT not between", value1, value2, "wdzt");
            return (Criteria) this;
        }

        public Criteria andNjlIsNull() {
            addCriterion("NJL is null");
            return (Criteria) this;
        }

        public Criteria andNjlIsNotNull() {
            addCriterion("NJL is not null");
            return (Criteria) this;
        }

        public Criteria andNjlEqualTo(BigDecimal value) {
            addCriterion("NJL =", value, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlNotEqualTo(BigDecimal value) {
            addCriterion("NJL <>", value, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlGreaterThan(BigDecimal value) {
            addCriterion("NJL >", value, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NJL >=", value, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlLessThan(BigDecimal value) {
            addCriterion("NJL <", value, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NJL <=", value, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlIn(List<BigDecimal> values) {
            addCriterion("NJL in", values, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlNotIn(List<BigDecimal> values) {
            addCriterion("NJL not in", values, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NJL between", value1, value2, "njl");
            return (Criteria) this;
        }

        public Criteria andNjlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NJL not between", value1, value2, "njl");
            return (Criteria) this;
        }

        public Criteria andNmcjIsNull() {
            addCriterion("NMCJ is null");
            return (Criteria) this;
        }

        public Criteria andNmcjIsNotNull() {
            addCriterion("NMCJ is not null");
            return (Criteria) this;
        }

        public Criteria andNmcjEqualTo(BigDecimal value) {
            addCriterion("NMCJ =", value, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjNotEqualTo(BigDecimal value) {
            addCriterion("NMCJ <>", value, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjGreaterThan(BigDecimal value) {
            addCriterion("NMCJ >", value, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NMCJ >=", value, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjLessThan(BigDecimal value) {
            addCriterion("NMCJ <", value, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NMCJ <=", value, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjIn(List<BigDecimal> values) {
            addCriterion("NMCJ in", values, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjNotIn(List<BigDecimal> values) {
            addCriterion("NMCJ not in", values, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NMCJ between", value1, value2, "nmcj");
            return (Criteria) this;
        }

        public Criteria andNmcjNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NMCJ not between", value1, value2, "nmcj");
            return (Criteria) this;
        }

        public Criteria andHdfxIsNull() {
            addCriterion("HDFX is null");
            return (Criteria) this;
        }

        public Criteria andHdfxIsNotNull() {
            addCriterion("HDFX is not null");
            return (Criteria) this;
        }

        public Criteria andHdfxEqualTo(String value) {
            addCriterion("HDFX =", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxNotEqualTo(String value) {
            addCriterion("HDFX <>", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxGreaterThan(String value) {
            addCriterion("HDFX >", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxGreaterThanOrEqualTo(String value) {
            addCriterion("HDFX >=", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxLessThan(String value) {
            addCriterion("HDFX <", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxLessThanOrEqualTo(String value) {
            addCriterion("HDFX <=", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxLike(String value) {
            addCriterion("HDFX like", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxNotLike(String value) {
            addCriterion("HDFX not like", value, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxIn(List<String> values) {
            addCriterion("HDFX in", values, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxNotIn(List<String> values) {
            addCriterion("HDFX not in", values, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxBetween(String value1, String value2) {
            addCriterion("HDFX between", value1, value2, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHdfxNotBetween(String value1, String value2) {
            addCriterion("HDFX not between", value1, value2, "hdfx");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcIsNull() {
            addCriterion("HPHYZDGC is null");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcIsNotNull() {
            addCriterion("HPHYZDGC is not null");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcEqualTo(BigDecimal value) {
            addCriterion("HPHYZDGC =", value, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcNotEqualTo(BigDecimal value) {
            addCriterion("HPHYZDGC <>", value, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcGreaterThan(BigDecimal value) {
            addCriterion("HPHYZDGC >", value, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HPHYZDGC >=", value, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcLessThan(BigDecimal value) {
            addCriterion("HPHYZDGC <", value, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HPHYZDGC <=", value, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcIn(List<BigDecimal> values) {
            addCriterion("HPHYZDGC in", values, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcNotIn(List<BigDecimal> values) {
            addCriterion("HPHYZDGC not in", values, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HPHYZDGC between", value1, value2, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHphyzdgcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HPHYZDGC not between", value1, value2, "hphyzdgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcIsNull() {
            addCriterion("HPQYZXGC is null");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcIsNotNull() {
            addCriterion("HPQYZXGC is not null");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcEqualTo(BigDecimal value) {
            addCriterion("HPQYZXGC =", value, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcNotEqualTo(BigDecimal value) {
            addCriterion("HPQYZXGC <>", value, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcGreaterThan(BigDecimal value) {
            addCriterion("HPQYZXGC >", value, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HPQYZXGC >=", value, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcLessThan(BigDecimal value) {
            addCriterion("HPQYZXGC <", value, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HPQYZXGC <=", value, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcIn(List<BigDecimal> values) {
            addCriterion("HPQYZXGC in", values, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcNotIn(List<BigDecimal> values) {
            addCriterion("HPQYZXGC not in", values, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HPQYZXGC between", value1, value2, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andHpqyzxgcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HPQYZXGC not between", value1, value2, "hpqyzxgc");
            return (Criteria) this;
        }

        public Criteria andDxswmsIsNull() {
            addCriterion("DXSWMS is null");
            return (Criteria) this;
        }

        public Criteria andDxswmsIsNotNull() {
            addCriterion("DXSWMS is not null");
            return (Criteria) this;
        }

        public Criteria andDxswmsEqualTo(BigDecimal value) {
            addCriterion("DXSWMS =", value, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsNotEqualTo(BigDecimal value) {
            addCriterion("DXSWMS <>", value, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsGreaterThan(BigDecimal value) {
            addCriterion("DXSWMS >", value, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DXSWMS >=", value, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsLessThan(BigDecimal value) {
            addCriterion("DXSWMS <", value, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DXSWMS <=", value, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsIn(List<BigDecimal> values) {
            addCriterion("DXSWMS in", values, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsNotIn(List<BigDecimal> values) {
            addCriterion("DXSWMS not in", values, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DXSWMS between", value1, value2, "dxswms");
            return (Criteria) this;
        }

        public Criteria andDxswmsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DXSWMS not between", value1, value2, "dxswms");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 02 15:45:25 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}