package cn.xjtu.zun.tiesheyuan.pojo;

public class DizhidiaohuiBuliangdizhiFangshexing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZ_FSXID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private Long dzdhBldzFsxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private Long dzdhBldzid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZ_FSXID
     *
     * @return the value of dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZ_FSXID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public Long getDzdhBldzFsxid() {
        return dzdhBldzFsxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZ_FSXID
     *
     * @param dzdhBldzFsxid the value for dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZ_FSXID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDzdhBldzFsxid(Long dzdhBldzFsxid) {
        this.dzdhBldzFsxid = dzdhBldzFsxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZID
     *
     * @return the value of dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public Long getDzdhBldzid() {
        return dzdhBldzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZID
     *
     * @param dzdhBldzid the value for dizhidiaohui_buliangdizhi_fangshexing.DZDH_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDzdhBldzid(Long dzdhBldzid) {
        this.dzdhBldzid = dzdhBldzid;
    }
}