package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class DizhidiaohuiBuliangdizhiNishiliu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZ_NSLID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private Long dzdhBldzNslid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private Long dzdhBldzid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.GKLC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal gklc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String lx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LYXT
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String lyxt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LTXZ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String ltxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.ZBQK
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String zbqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.GM
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String gm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.PL
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String pl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.FYJD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String fyjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.XCQYX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String xcqyx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.XCQWZZC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String xcqwzzc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.XCQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String xcqms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LTQCD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal ltqcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LTQKD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal ltqkd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LTQGZ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal ltqgz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.LTQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String ltqms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DJQWZZC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String djqwzzc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DJQMJ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal djqmj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DJQHD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal djqhd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DJQPD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private BigDecimal djqpd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.DJQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String djqms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.YFX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String yfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dizhidiaohui_buliangdizhi_nishiliu.WHCD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    private String whcd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZ_NSLID
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZ_NSLID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public Long getDzdhBldzNslid() {
        return dzdhBldzNslid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZ_NSLID
     *
     * @param dzdhBldzNslid the value for dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZ_NSLID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDzdhBldzNslid(Long dzdhBldzNslid) {
        this.dzdhBldzNslid = dzdhBldzNslid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZID
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public Long getDzdhBldzid() {
        return dzdhBldzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZID
     *
     * @param dzdhBldzid the value for dizhidiaohui_buliangdizhi_nishiliu.DZDH_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDzdhBldzid(Long dzdhBldzid) {
        this.dzdhBldzid = dzdhBldzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.GKLC
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.GKLC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getGklc() {
        return gklc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.GKLC
     *
     * @param gklc the value for dizhidiaohui_buliangdizhi_nishiliu.GKLC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setGklc(BigDecimal gklc) {
        this.gklc = gklc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LX
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LX
     *
     * @param lx the value for dizhidiaohui_buliangdizhi_nishiliu.LX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LYXT
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LYXT
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getLyxt() {
        return lyxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LYXT
     *
     * @param lyxt the value for dizhidiaohui_buliangdizhi_nishiliu.LYXT
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLyxt(String lyxt) {
        this.lyxt = lyxt == null ? null : lyxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTXZ
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LTXZ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getLtxz() {
        return ltxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTXZ
     *
     * @param ltxz the value for dizhidiaohui_buliangdizhi_nishiliu.LTXZ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLtxz(String ltxz) {
        this.ltxz = ltxz == null ? null : ltxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.ZBQK
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.ZBQK
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getZbqk() {
        return zbqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.ZBQK
     *
     * @param zbqk the value for dizhidiaohui_buliangdizhi_nishiliu.ZBQK
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setZbqk(String zbqk) {
        this.zbqk = zbqk == null ? null : zbqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.GM
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.GM
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getGm() {
        return gm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.GM
     *
     * @param gm the value for dizhidiaohui_buliangdizhi_nishiliu.GM
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setGm(String gm) {
        this.gm = gm == null ? null : gm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.PL
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.PL
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.PL
     *
     * @param pl the value for dizhidiaohui_buliangdizhi_nishiliu.PL
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setPl(String pl) {
        this.pl = pl == null ? null : pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.FYJD
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.FYJD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getFyjd() {
        return fyjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.FYJD
     *
     * @param fyjd the value for dizhidiaohui_buliangdizhi_nishiliu.FYJD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setFyjd(String fyjd) {
        this.fyjd = fyjd == null ? null : fyjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.XCQYX
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.XCQYX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getXcqyx() {
        return xcqyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.XCQYX
     *
     * @param xcqyx the value for dizhidiaohui_buliangdizhi_nishiliu.XCQYX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setXcqyx(String xcqyx) {
        this.xcqyx = xcqyx == null ? null : xcqyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.XCQWZZC
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.XCQWZZC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getXcqwzzc() {
        return xcqwzzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.XCQWZZC
     *
     * @param xcqwzzc the value for dizhidiaohui_buliangdizhi_nishiliu.XCQWZZC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setXcqwzzc(String xcqwzzc) {
        this.xcqwzzc = xcqwzzc == null ? null : xcqwzzc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.XCQMS
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.XCQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getXcqms() {
        return xcqms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.XCQMS
     *
     * @param xcqms the value for dizhidiaohui_buliangdizhi_nishiliu.XCQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setXcqms(String xcqms) {
        this.xcqms = xcqms == null ? null : xcqms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQCD
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LTQCD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getLtqcd() {
        return ltqcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQCD
     *
     * @param ltqcd the value for dizhidiaohui_buliangdizhi_nishiliu.LTQCD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLtqcd(BigDecimal ltqcd) {
        this.ltqcd = ltqcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQKD
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LTQKD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getLtqkd() {
        return ltqkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQKD
     *
     * @param ltqkd the value for dizhidiaohui_buliangdizhi_nishiliu.LTQKD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLtqkd(BigDecimal ltqkd) {
        this.ltqkd = ltqkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQGZ
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LTQGZ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getLtqgz() {
        return ltqgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQGZ
     *
     * @param ltqgz the value for dizhidiaohui_buliangdizhi_nishiliu.LTQGZ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLtqgz(BigDecimal ltqgz) {
        this.ltqgz = ltqgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQMS
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.LTQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getLtqms() {
        return ltqms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.LTQMS
     *
     * @param ltqms the value for dizhidiaohui_buliangdizhi_nishiliu.LTQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setLtqms(String ltqms) {
        this.ltqms = ltqms == null ? null : ltqms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQWZZC
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DJQWZZC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getDjqwzzc() {
        return djqwzzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQWZZC
     *
     * @param djqwzzc the value for dizhidiaohui_buliangdizhi_nishiliu.DJQWZZC
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDjqwzzc(String djqwzzc) {
        this.djqwzzc = djqwzzc == null ? null : djqwzzc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQMJ
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DJQMJ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getDjqmj() {
        return djqmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQMJ
     *
     * @param djqmj the value for dizhidiaohui_buliangdizhi_nishiliu.DJQMJ
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDjqmj(BigDecimal djqmj) {
        this.djqmj = djqmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQHD
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DJQHD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getDjqhd() {
        return djqhd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQHD
     *
     * @param djqhd the value for dizhidiaohui_buliangdizhi_nishiliu.DJQHD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDjqhd(BigDecimal djqhd) {
        this.djqhd = djqhd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQPD
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DJQPD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public BigDecimal getDjqpd() {
        return djqpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQPD
     *
     * @param djqpd the value for dizhidiaohui_buliangdizhi_nishiliu.DJQPD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDjqpd(BigDecimal djqpd) {
        this.djqpd = djqpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQMS
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.DJQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getDjqms() {
        return djqms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.DJQMS
     *
     * @param djqms the value for dizhidiaohui_buliangdizhi_nishiliu.DJQMS
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setDjqms(String djqms) {
        this.djqms = djqms == null ? null : djqms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.YFX
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.YFX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getYfx() {
        return yfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.YFX
     *
     * @param yfx the value for dizhidiaohui_buliangdizhi_nishiliu.YFX
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setYfx(String yfx) {
        this.yfx = yfx == null ? null : yfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dizhidiaohui_buliangdizhi_nishiliu.WHCD
     *
     * @return the value of dizhidiaohui_buliangdizhi_nishiliu.WHCD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public String getWhcd() {
        return whcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dizhidiaohui_buliangdizhi_nishiliu.WHCD
     *
     * @param whcd the value for dizhidiaohui_buliangdizhi_nishiliu.WHCD
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    public void setWhcd(String whcd) {
        this.whcd = whcd == null ? null : whcd.trim();
    }
}