package cn.xjtu.zun.tiesheyuan.pojo;

public class DuanluochengguoPingmiantu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.ID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.PROJECT_INFORMATION_DATA_CLASSIFICATION_ID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long projectInformationDataClassificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.FILE_NAME
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.FILE_TYPE
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.FILE_SIZE
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.FILE_PATH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.belong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duanluochengguo_pingmiantu.bid
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long bid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.ID
     *
     * @return the value of duanluochengguo_pingmiantu.ID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.ID
     *
     * @param id the value for duanluochengguo_pingmiantu.ID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.PROJECT_INFORMATION_DATA_CLASSIFICATION_ID
     *
     * @return the value of duanluochengguo_pingmiantu.PROJECT_INFORMATION_DATA_CLASSIFICATION_ID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getProjectInformationDataClassificationId() {
        return projectInformationDataClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.PROJECT_INFORMATION_DATA_CLASSIFICATION_ID
     *
     * @param projectInformationDataClassificationId the value for duanluochengguo_pingmiantu.PROJECT_INFORMATION_DATA_CLASSIFICATION_ID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setProjectInformationDataClassificationId(Long projectInformationDataClassificationId) {
        this.projectInformationDataClassificationId = projectInformationDataClassificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.FILE_NAME
     *
     * @return the value of duanluochengguo_pingmiantu.FILE_NAME
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.FILE_NAME
     *
     * @param fileName the value for duanluochengguo_pingmiantu.FILE_NAME
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.FILE_TYPE
     *
     * @return the value of duanluochengguo_pingmiantu.FILE_TYPE
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.FILE_TYPE
     *
     * @param fileType the value for duanluochengguo_pingmiantu.FILE_TYPE
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.FILE_SIZE
     *
     * @return the value of duanluochengguo_pingmiantu.FILE_SIZE
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.FILE_SIZE
     *
     * @param fileSize the value for duanluochengguo_pingmiantu.FILE_SIZE
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize == null ? null : fileSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.FILE_PATH
     *
     * @return the value of duanluochengguo_pingmiantu.FILE_PATH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.FILE_PATH
     *
     * @param filePath the value for duanluochengguo_pingmiantu.FILE_PATH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.belong
     *
     * @return the value of duanluochengguo_pingmiantu.belong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.belong
     *
     * @param belong the value for duanluochengguo_pingmiantu.belong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duanluochengguo_pingmiantu.bid
     *
     * @return the value of duanluochengguo_pingmiantu.bid
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duanluochengguo_pingmiantu.bid
     *
     * @param bid the value for duanluochengguo_pingmiantu.bid
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }
}