package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class JingtanLuoxuanbanzaiheExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public JingtanLuoxuanbanzaiheExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJtLxbzhidIsNull() {
            addCriterion("JT_LXBZHID is null");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidIsNotNull() {
            addCriterion("JT_LXBZHID is not null");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidEqualTo(Long value) {
            addCriterion("JT_LXBZHID =", value, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidNotEqualTo(Long value) {
            addCriterion("JT_LXBZHID <>", value, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidGreaterThan(Long value) {
            addCriterion("JT_LXBZHID >", value, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidGreaterThanOrEqualTo(Long value) {
            addCriterion("JT_LXBZHID >=", value, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidLessThan(Long value) {
            addCriterion("JT_LXBZHID <", value, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidLessThanOrEqualTo(Long value) {
            addCriterion("JT_LXBZHID <=", value, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidIn(List<Long> values) {
            addCriterion("JT_LXBZHID in", values, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidNotIn(List<Long> values) {
            addCriterion("JT_LXBZHID not in", values, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidBetween(Long value1, Long value2) {
            addCriterion("JT_LXBZHID between", value1, value2, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtLxbzhidNotBetween(Long value1, Long value2) {
            addCriterion("JT_LXBZHID not between", value1, value2, "jtLxbzhid");
            return (Criteria) this;
        }

        public Criteria andJtidIsNull() {
            addCriterion("JTID is null");
            return (Criteria) this;
        }

        public Criteria andJtidIsNotNull() {
            addCriterion("JTID is not null");
            return (Criteria) this;
        }

        public Criteria andJtidEqualTo(Long value) {
            addCriterion("JTID =", value, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidNotEqualTo(Long value) {
            addCriterion("JTID <>", value, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidGreaterThan(Long value) {
            addCriterion("JTID >", value, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidGreaterThanOrEqualTo(Long value) {
            addCriterion("JTID >=", value, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidLessThan(Long value) {
            addCriterion("JTID <", value, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidLessThanOrEqualTo(Long value) {
            addCriterion("JTID <=", value, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidIn(List<Long> values) {
            addCriterion("JTID in", values, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidNotIn(List<Long> values) {
            addCriterion("JTID not in", values, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidBetween(Long value1, Long value2) {
            addCriterion("JTID between", value1, value2, "jtid");
            return (Criteria) this;
        }

        public Criteria andJtidNotBetween(Long value1, Long value2) {
            addCriterion("JTID not between", value1, value2, "jtid");
            return (Criteria) this;
        }

        public Criteria andSysdIsNull() {
            addCriterion("SYSD is null");
            return (Criteria) this;
        }

        public Criteria andSysdIsNotNull() {
            addCriterion("SYSD is not null");
            return (Criteria) this;
        }

        public Criteria andSysdEqualTo(BigDecimal value) {
            addCriterion("SYSD =", value, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdNotEqualTo(BigDecimal value) {
            addCriterion("SYSD <>", value, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdGreaterThan(BigDecimal value) {
            addCriterion("SYSD >", value, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SYSD >=", value, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdLessThan(BigDecimal value) {
            addCriterion("SYSD <", value, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SYSD <=", value, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdIn(List<BigDecimal> values) {
            addCriterion("SYSD in", values, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdNotIn(List<BigDecimal> values) {
            addCriterion("SYSD not in", values, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SYSD between", value1, value2, "sysd");
            return (Criteria) this;
        }

        public Criteria andSysdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SYSD not between", value1, value2, "sysd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 02 15:45:26 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jingtan_luoxuanbanzaihe
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}