package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class JingtanKongyaxiaosan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingtan_kongyaxiaosan.JT_KYXSID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long jtKyxsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingtan_kongyaxiaosan.JTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long jtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingtan_kongyaxiaosan.SYBH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String sybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingtan_kongyaxiaosan.SDXS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sdxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingtan_kongyaxiaosan.SYRQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Date syrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingtan_kongyaxiaosan.BZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingtan_kongyaxiaosan.JT_KYXSID
     *
     * @return the value of jingtan_kongyaxiaosan.JT_KYXSID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getJtKyxsid() {
        return jtKyxsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingtan_kongyaxiaosan.JT_KYXSID
     *
     * @param jtKyxsid the value for jingtan_kongyaxiaosan.JT_KYXSID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJtKyxsid(Long jtKyxsid) {
        this.jtKyxsid = jtKyxsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingtan_kongyaxiaosan.JTID
     *
     * @return the value of jingtan_kongyaxiaosan.JTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getJtid() {
        return jtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingtan_kongyaxiaosan.JTID
     *
     * @param jtid the value for jingtan_kongyaxiaosan.JTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJtid(Long jtid) {
        this.jtid = jtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingtan_kongyaxiaosan.SYBH
     *
     * @return the value of jingtan_kongyaxiaosan.SYBH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getSybh() {
        return sybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingtan_kongyaxiaosan.SYBH
     *
     * @param sybh the value for jingtan_kongyaxiaosan.SYBH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSybh(String sybh) {
        this.sybh = sybh == null ? null : sybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingtan_kongyaxiaosan.SDXS
     *
     * @return the value of jingtan_kongyaxiaosan.SDXS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSdxs() {
        return sdxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingtan_kongyaxiaosan.SDXS
     *
     * @param sdxs the value for jingtan_kongyaxiaosan.SDXS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdxs(BigDecimal sdxs) {
        this.sdxs = sdxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingtan_kongyaxiaosan.SYRQ
     *
     * @return the value of jingtan_kongyaxiaosan.SYRQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Date getSyrq() {
        return syrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingtan_kongyaxiaosan.SYRQ
     *
     * @param syrq the value for jingtan_kongyaxiaosan.SYRQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSyrq(Date syrq) {
        this.syrq = syrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingtan_kongyaxiaosan.BZ
     *
     * @return the value of jingtan_kongyaxiaosan.BZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingtan_kongyaxiaosan.BZ
     *
     * @param bz the value for jingtan_kongyaxiaosan.BZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}