package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Qixiangziliao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QXZLID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long qxzlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.XMMCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String xmmcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.ZTMC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String ztmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JZSJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Date jzsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.DLWZJHBGC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String dlwzjhbgc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.DBLCJDD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String dblcjdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.PJQY
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal pjqy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QW_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qwNpj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QW_JDZG
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qwJdzg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QW_JDZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qwJdzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QW_ZRYPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qwZrypj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QW_ZLYPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qwZlypj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.QW_PJNJC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qwPjnjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.SD_JDNPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sdJdnpj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.SD_JDZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sdJdzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.SD_JDZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sdJdzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.SD_XDPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sdXdpj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.SD_XDZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sdXdzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslNpj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_NZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslNzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_NZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslNzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_YZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslYzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_YZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslYzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_RZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslRzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_YCZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jslYczd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_YCZDYXSJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Integer jslYczdyxsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.JSL_NPJJSRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Integer jslNpjjsrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.ZFL_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zflNpj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.ZFL_NZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zflNzd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_NPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fNpjfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_NZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fNzdfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_CJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fCjpjfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_CJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fCjzdfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_XJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fXjpjfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_XJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fXjzdfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_QJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fQjpjfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_QJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fQjzdfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_DJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fDjpjfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_DJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fDjzdfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_NJDFRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Integer fNjdfrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_ZDFSDS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fZdfsds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_ZDFFXDS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fZdffxds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_ZDFSSS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal fZdfsss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.F_ZDFFXSS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fZdffxss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.XD_JXCZQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String xdJxczq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.XD_ZDJXHD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal xdZdjxhd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.XD_JDTCZQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String xdJdtczq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.XD_ZDJJDTSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal xdZdjjdtsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.PJWTRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Integer pjwtrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qixiangziliao.PJLTRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Integer pjltrs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QXZLID
     *
     * @return the value of qixiangziliao.QXZLID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getQxzlid() {
        return qxzlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QXZLID
     *
     * @param qxzlid the value for qixiangziliao.QXZLID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQxzlid(Long qxzlid) {
        this.qxzlid = qxzlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.XMMCID
     *
     * @return the value of qixiangziliao.XMMCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getXmmcid() {
        return xmmcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.XMMCID
     *
     * @param xmmcid the value for qixiangziliao.XMMCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXmmcid(String xmmcid) {
        this.xmmcid = xmmcid == null ? null : xmmcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.ZTMC
     *
     * @return the value of qixiangziliao.ZTMC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getZtmc() {
        return ztmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.ZTMC
     *
     * @param ztmc the value for qixiangziliao.ZTMC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZtmc(String ztmc) {
        this.ztmc = ztmc == null ? null : ztmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JZSJ
     *
     * @return the value of qixiangziliao.JZSJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Date getJzsj() {
        return jzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JZSJ
     *
     * @param jzsj the value for qixiangziliao.JZSJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJzsj(Date jzsj) {
        this.jzsj = jzsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.DLWZJHBGC
     *
     * @return the value of qixiangziliao.DLWZJHBGC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getDlwzjhbgc() {
        return dlwzjhbgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.DLWZJHBGC
     *
     * @param dlwzjhbgc the value for qixiangziliao.DLWZJHBGC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDlwzjhbgc(String dlwzjhbgc) {
        this.dlwzjhbgc = dlwzjhbgc == null ? null : dlwzjhbgc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.DBLCJDD
     *
     * @return the value of qixiangziliao.DBLCJDD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getDblcjdd() {
        return dblcjdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.DBLCJDD
     *
     * @param dblcjdd the value for qixiangziliao.DBLCJDD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDblcjdd(String dblcjdd) {
        this.dblcjdd = dblcjdd == null ? null : dblcjdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.PJQY
     *
     * @return the value of qixiangziliao.PJQY
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getPjqy() {
        return pjqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.PJQY
     *
     * @param pjqy the value for qixiangziliao.PJQY
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setPjqy(BigDecimal pjqy) {
        this.pjqy = pjqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QW_NPJ
     *
     * @return the value of qixiangziliao.QW_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQwNpj() {
        return qwNpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QW_NPJ
     *
     * @param qwNpj the value for qixiangziliao.QW_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQwNpj(BigDecimal qwNpj) {
        this.qwNpj = qwNpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QW_JDZG
     *
     * @return the value of qixiangziliao.QW_JDZG
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQwJdzg() {
        return qwJdzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QW_JDZG
     *
     * @param qwJdzg the value for qixiangziliao.QW_JDZG
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQwJdzg(BigDecimal qwJdzg) {
        this.qwJdzg = qwJdzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QW_JDZD
     *
     * @return the value of qixiangziliao.QW_JDZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQwJdzd() {
        return qwJdzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QW_JDZD
     *
     * @param qwJdzd the value for qixiangziliao.QW_JDZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQwJdzd(BigDecimal qwJdzd) {
        this.qwJdzd = qwJdzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QW_ZRYPJ
     *
     * @return the value of qixiangziliao.QW_ZRYPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQwZrypj() {
        return qwZrypj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QW_ZRYPJ
     *
     * @param qwZrypj the value for qixiangziliao.QW_ZRYPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQwZrypj(BigDecimal qwZrypj) {
        this.qwZrypj = qwZrypj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QW_ZLYPJ
     *
     * @return the value of qixiangziliao.QW_ZLYPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQwZlypj() {
        return qwZlypj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QW_ZLYPJ
     *
     * @param qwZlypj the value for qixiangziliao.QW_ZLYPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQwZlypj(BigDecimal qwZlypj) {
        this.qwZlypj = qwZlypj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.QW_PJNJC
     *
     * @return the value of qixiangziliao.QW_PJNJC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQwPjnjc() {
        return qwPjnjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.QW_PJNJC
     *
     * @param qwPjnjc the value for qixiangziliao.QW_PJNJC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQwPjnjc(BigDecimal qwPjnjc) {
        this.qwPjnjc = qwPjnjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.SD_JDNPJ
     *
     * @return the value of qixiangziliao.SD_JDNPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSdJdnpj() {
        return sdJdnpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.SD_JDNPJ
     *
     * @param sdJdnpj the value for qixiangziliao.SD_JDNPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdJdnpj(BigDecimal sdJdnpj) {
        this.sdJdnpj = sdJdnpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.SD_JDZD
     *
     * @return the value of qixiangziliao.SD_JDZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSdJdzd() {
        return sdJdzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.SD_JDZD
     *
     * @param sdJdzd the value for qixiangziliao.SD_JDZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdJdzd(BigDecimal sdJdzd) {
        this.sdJdzd = sdJdzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.SD_JDZX
     *
     * @return the value of qixiangziliao.SD_JDZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSdJdzx() {
        return sdJdzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.SD_JDZX
     *
     * @param sdJdzx the value for qixiangziliao.SD_JDZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdJdzx(BigDecimal sdJdzx) {
        this.sdJdzx = sdJdzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.SD_XDPJ
     *
     * @return the value of qixiangziliao.SD_XDPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSdXdpj() {
        return sdXdpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.SD_XDPJ
     *
     * @param sdXdpj the value for qixiangziliao.SD_XDPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdXdpj(BigDecimal sdXdpj) {
        this.sdXdpj = sdXdpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.SD_XDZX
     *
     * @return the value of qixiangziliao.SD_XDZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSdXdzx() {
        return sdXdzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.SD_XDZX
     *
     * @param sdXdzx the value for qixiangziliao.SD_XDZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdXdzx(BigDecimal sdXdzx) {
        this.sdXdzx = sdXdzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_NPJ
     *
     * @return the value of qixiangziliao.JSL_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslNpj() {
        return jslNpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_NPJ
     *
     * @param jslNpj the value for qixiangziliao.JSL_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslNpj(BigDecimal jslNpj) {
        this.jslNpj = jslNpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_NZD
     *
     * @return the value of qixiangziliao.JSL_NZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslNzd() {
        return jslNzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_NZD
     *
     * @param jslNzd the value for qixiangziliao.JSL_NZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslNzd(BigDecimal jslNzd) {
        this.jslNzd = jslNzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_NZX
     *
     * @return the value of qixiangziliao.JSL_NZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslNzx() {
        return jslNzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_NZX
     *
     * @param jslNzx the value for qixiangziliao.JSL_NZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslNzx(BigDecimal jslNzx) {
        this.jslNzx = jslNzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_YZD
     *
     * @return the value of qixiangziliao.JSL_YZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslYzd() {
        return jslYzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_YZD
     *
     * @param jslYzd the value for qixiangziliao.JSL_YZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslYzd(BigDecimal jslYzd) {
        this.jslYzd = jslYzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_YZX
     *
     * @return the value of qixiangziliao.JSL_YZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslYzx() {
        return jslYzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_YZX
     *
     * @param jslYzx the value for qixiangziliao.JSL_YZX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslYzx(BigDecimal jslYzx) {
        this.jslYzx = jslYzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_RZD
     *
     * @return the value of qixiangziliao.JSL_RZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslRzd() {
        return jslRzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_RZD
     *
     * @param jslRzd the value for qixiangziliao.JSL_RZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslRzd(BigDecimal jslRzd) {
        this.jslRzd = jslRzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_YCZD
     *
     * @return the value of qixiangziliao.JSL_YCZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJslYczd() {
        return jslYczd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_YCZD
     *
     * @param jslYczd the value for qixiangziliao.JSL_YCZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslYczd(BigDecimal jslYczd) {
        this.jslYczd = jslYczd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_YCZDYXSJ
     *
     * @return the value of qixiangziliao.JSL_YCZDYXSJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Integer getJslYczdyxsj() {
        return jslYczdyxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_YCZDYXSJ
     *
     * @param jslYczdyxsj the value for qixiangziliao.JSL_YCZDYXSJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslYczdyxsj(Integer jslYczdyxsj) {
        this.jslYczdyxsj = jslYczdyxsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.JSL_NPJJSRS
     *
     * @return the value of qixiangziliao.JSL_NPJJSRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Integer getJslNpjjsrs() {
        return jslNpjjsrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.JSL_NPJJSRS
     *
     * @param jslNpjjsrs the value for qixiangziliao.JSL_NPJJSRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJslNpjjsrs(Integer jslNpjjsrs) {
        this.jslNpjjsrs = jslNpjjsrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.ZFL_NPJ
     *
     * @return the value of qixiangziliao.ZFL_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZflNpj() {
        return zflNpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.ZFL_NPJ
     *
     * @param zflNpj the value for qixiangziliao.ZFL_NPJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZflNpj(BigDecimal zflNpj) {
        this.zflNpj = zflNpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.ZFL_NZD
     *
     * @return the value of qixiangziliao.ZFL_NZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZflNzd() {
        return zflNzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.ZFL_NZD
     *
     * @param zflNzd the value for qixiangziliao.ZFL_NZD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZflNzd(BigDecimal zflNzd) {
        this.zflNzd = zflNzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_NPJFS
     *
     * @return the value of qixiangziliao.F_NPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfNpjfs() {
        return fNpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_NPJFS
     *
     * @param fNpjfs the value for qixiangziliao.F_NPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfNpjfs(BigDecimal fNpjfs) {
        this.fNpjfs = fNpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_NZDFX
     *
     * @return the value of qixiangziliao.F_NZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfNzdfx() {
        return fNzdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_NZDFX
     *
     * @param fNzdfx the value for qixiangziliao.F_NZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfNzdfx(String fNzdfx) {
        this.fNzdfx = fNzdfx == null ? null : fNzdfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_CJPJFS
     *
     * @return the value of qixiangziliao.F_CJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfCjpjfs() {
        return fCjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_CJPJFS
     *
     * @param fCjpjfs the value for qixiangziliao.F_CJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfCjpjfs(BigDecimal fCjpjfs) {
        this.fCjpjfs = fCjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_CJZDFX
     *
     * @return the value of qixiangziliao.F_CJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfCjzdfx() {
        return fCjzdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_CJZDFX
     *
     * @param fCjzdfx the value for qixiangziliao.F_CJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfCjzdfx(String fCjzdfx) {
        this.fCjzdfx = fCjzdfx == null ? null : fCjzdfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_XJPJFS
     *
     * @return the value of qixiangziliao.F_XJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfXjpjfs() {
        return fXjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_XJPJFS
     *
     * @param fXjpjfs the value for qixiangziliao.F_XJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfXjpjfs(BigDecimal fXjpjfs) {
        this.fXjpjfs = fXjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_XJZDFX
     *
     * @return the value of qixiangziliao.F_XJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfXjzdfx() {
        return fXjzdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_XJZDFX
     *
     * @param fXjzdfx the value for qixiangziliao.F_XJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfXjzdfx(String fXjzdfx) {
        this.fXjzdfx = fXjzdfx == null ? null : fXjzdfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_QJPJFS
     *
     * @return the value of qixiangziliao.F_QJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfQjpjfs() {
        return fQjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_QJPJFS
     *
     * @param fQjpjfs the value for qixiangziliao.F_QJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfQjpjfs(BigDecimal fQjpjfs) {
        this.fQjpjfs = fQjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_QJZDFX
     *
     * @return the value of qixiangziliao.F_QJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfQjzdfx() {
        return fQjzdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_QJZDFX
     *
     * @param fQjzdfx the value for qixiangziliao.F_QJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfQjzdfx(String fQjzdfx) {
        this.fQjzdfx = fQjzdfx == null ? null : fQjzdfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_DJPJFS
     *
     * @return the value of qixiangziliao.F_DJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfDjpjfs() {
        return fDjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_DJPJFS
     *
     * @param fDjpjfs the value for qixiangziliao.F_DJPJFS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfDjpjfs(BigDecimal fDjpjfs) {
        this.fDjpjfs = fDjpjfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_DJZDFX
     *
     * @return the value of qixiangziliao.F_DJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfDjzdfx() {
        return fDjzdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_DJZDFX
     *
     * @param fDjzdfx the value for qixiangziliao.F_DJZDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfDjzdfx(String fDjzdfx) {
        this.fDjzdfx = fDjzdfx == null ? null : fDjzdfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_NJDFRS
     *
     * @return the value of qixiangziliao.F_NJDFRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Integer getfNjdfrs() {
        return fNjdfrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_NJDFRS
     *
     * @param fNjdfrs the value for qixiangziliao.F_NJDFRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfNjdfrs(Integer fNjdfrs) {
        this.fNjdfrs = fNjdfrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_ZDFSDS
     *
     * @return the value of qixiangziliao.F_ZDFSDS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfZdfsds() {
        return fZdfsds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_ZDFSDS
     *
     * @param fZdfsds the value for qixiangziliao.F_ZDFSDS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfZdfsds(BigDecimal fZdfsds) {
        this.fZdfsds = fZdfsds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_ZDFFXDS
     *
     * @return the value of qixiangziliao.F_ZDFFXDS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfZdffxds() {
        return fZdffxds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_ZDFFXDS
     *
     * @param fZdffxds the value for qixiangziliao.F_ZDFFXDS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfZdffxds(String fZdffxds) {
        this.fZdffxds = fZdffxds == null ? null : fZdffxds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_ZDFSSS
     *
     * @return the value of qixiangziliao.F_ZDFSSS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getfZdfsss() {
        return fZdfsss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_ZDFSSS
     *
     * @param fZdfsss the value for qixiangziliao.F_ZDFSSS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfZdfsss(BigDecimal fZdfsss) {
        this.fZdfsss = fZdfsss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.F_ZDFFXSS
     *
     * @return the value of qixiangziliao.F_ZDFFXSS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getfZdffxss() {
        return fZdffxss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.F_ZDFFXSS
     *
     * @param fZdffxss the value for qixiangziliao.F_ZDFFXSS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setfZdffxss(String fZdffxss) {
        this.fZdffxss = fZdffxss == null ? null : fZdffxss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.XD_JXCZQ
     *
     * @return the value of qixiangziliao.XD_JXCZQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getXdJxczq() {
        return xdJxczq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.XD_JXCZQ
     *
     * @param xdJxczq the value for qixiangziliao.XD_JXCZQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXdJxczq(String xdJxczq) {
        this.xdJxczq = xdJxczq == null ? null : xdJxczq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.XD_ZDJXHD
     *
     * @return the value of qixiangziliao.XD_ZDJXHD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getXdZdjxhd() {
        return xdZdjxhd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.XD_ZDJXHD
     *
     * @param xdZdjxhd the value for qixiangziliao.XD_ZDJXHD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXdZdjxhd(BigDecimal xdZdjxhd) {
        this.xdZdjxhd = xdZdjxhd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.XD_JDTCZQ
     *
     * @return the value of qixiangziliao.XD_JDTCZQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getXdJdtczq() {
        return xdJdtczq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.XD_JDTCZQ
     *
     * @param xdJdtczq the value for qixiangziliao.XD_JDTCZQ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXdJdtczq(String xdJdtczq) {
        this.xdJdtczq = xdJdtczq == null ? null : xdJdtczq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.XD_ZDJJDTSD
     *
     * @return the value of qixiangziliao.XD_ZDJJDTSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getXdZdjjdtsd() {
        return xdZdjjdtsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.XD_ZDJJDTSD
     *
     * @param xdZdjjdtsd the value for qixiangziliao.XD_ZDJJDTSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXdZdjjdtsd(BigDecimal xdZdjjdtsd) {
        this.xdZdjjdtsd = xdZdjjdtsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.PJWTRS
     *
     * @return the value of qixiangziliao.PJWTRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Integer getPjwtrs() {
        return pjwtrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.PJWTRS
     *
     * @param pjwtrs the value for qixiangziliao.PJWTRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setPjwtrs(Integer pjwtrs) {
        this.pjwtrs = pjwtrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qixiangziliao.PJLTRS
     *
     * @return the value of qixiangziliao.PJLTRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Integer getPjltrs() {
        return pjltrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qixiangziliao.PJLTRS
     *
     * @param pjltrs the value for qixiangziliao.PJLTRS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setPjltrs(Integer pjltrs) {
        this.pjltrs = pjltrs;
    }
}