package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class QuyudizhiziliaoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public QuyudizhiziliaoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQydzzlidIsNull() {
            addCriterion("QYDZZLID is null");
            return (Criteria) this;
        }

        public Criteria andQydzzlidIsNotNull() {
            addCriterion("QYDZZLID is not null");
            return (Criteria) this;
        }

        public Criteria andQydzzlidEqualTo(Long value) {
            addCriterion("QYDZZLID =", value, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidNotEqualTo(Long value) {
            addCriterion("QYDZZLID <>", value, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidGreaterThan(Long value) {
            addCriterion("QYDZZLID >", value, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidGreaterThanOrEqualTo(Long value) {
            addCriterion("QYDZZLID >=", value, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidLessThan(Long value) {
            addCriterion("QYDZZLID <", value, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidLessThanOrEqualTo(Long value) {
            addCriterion("QYDZZLID <=", value, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidIn(List<Long> values) {
            addCriterion("QYDZZLID in", values, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidNotIn(List<Long> values) {
            addCriterion("QYDZZLID not in", values, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidBetween(Long value1, Long value2) {
            addCriterion("QYDZZLID between", value1, value2, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andQydzzlidNotBetween(Long value1, Long value2) {
            addCriterion("QYDZZLID not between", value1, value2, "qydzzlid");
            return (Criteria) this;
        }

        public Criteria andXmmcidIsNull() {
            addCriterion("XMMCID is null");
            return (Criteria) this;
        }

        public Criteria andXmmcidIsNotNull() {
            addCriterion("XMMCID is not null");
            return (Criteria) this;
        }

        public Criteria andXmmcidEqualTo(String value) {
            addCriterion("XMMCID =", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidNotEqualTo(String value) {
            addCriterion("XMMCID <>", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidGreaterThan(String value) {
            addCriterion("XMMCID >", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidGreaterThanOrEqualTo(String value) {
            addCriterion("XMMCID >=", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidLessThan(String value) {
            addCriterion("XMMCID <", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidLessThanOrEqualTo(String value) {
            addCriterion("XMMCID <=", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidLike(String value) {
            addCriterion("XMMCID like", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidNotLike(String value) {
            addCriterion("XMMCID not like", value, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidIn(List<String> values) {
            addCriterion("XMMCID in", values, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidNotIn(List<String> values) {
            addCriterion("XMMCID not in", values, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidBetween(String value1, String value2) {
            addCriterion("XMMCID between", value1, value2, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andXmmcidNotBetween(String value1, String value2) {
            addCriterion("XMMCID not between", value1, value2, "xmmcid");
            return (Criteria) this;
        }

        public Criteria andLxIsNull() {
            addCriterion("LX is null");
            return (Criteria) this;
        }

        public Criteria andLxIsNotNull() {
            addCriterion("LX is not null");
            return (Criteria) this;
        }

        public Criteria andLxEqualTo(String value) {
            addCriterion("LX =", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotEqualTo(String value) {
            addCriterion("LX <>", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxGreaterThan(String value) {
            addCriterion("LX >", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxGreaterThanOrEqualTo(String value) {
            addCriterion("LX >=", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLessThan(String value) {
            addCriterion("LX <", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLessThanOrEqualTo(String value) {
            addCriterion("LX <=", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxLike(String value) {
            addCriterion("LX like", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotLike(String value) {
            addCriterion("LX not like", value, "lx");
            return (Criteria) this;
        }

        public Criteria andLxIn(List<String> values) {
            addCriterion("LX in", values, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotIn(List<String> values) {
            addCriterion("LX not in", values, "lx");
            return (Criteria) this;
        }

        public Criteria andLxBetween(String value1, String value2) {
            addCriterion("LX between", value1, value2, "lx");
            return (Criteria) this;
        }

        public Criteria andLxNotBetween(String value1, String value2) {
            addCriterion("LX not between", value1, value2, "lx");
            return (Criteria) this;
        }

        public Criteria andTfmcIsNull() {
            addCriterion("TFMC is null");
            return (Criteria) this;
        }

        public Criteria andTfmcIsNotNull() {
            addCriterion("TFMC is not null");
            return (Criteria) this;
        }

        public Criteria andTfmcEqualTo(String value) {
            addCriterion("TFMC =", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcNotEqualTo(String value) {
            addCriterion("TFMC <>", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcGreaterThan(String value) {
            addCriterion("TFMC >", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcGreaterThanOrEqualTo(String value) {
            addCriterion("TFMC >=", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcLessThan(String value) {
            addCriterion("TFMC <", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcLessThanOrEqualTo(String value) {
            addCriterion("TFMC <=", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcLike(String value) {
            addCriterion("TFMC like", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcNotLike(String value) {
            addCriterion("TFMC not like", value, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcIn(List<String> values) {
            addCriterion("TFMC in", values, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcNotIn(List<String> values) {
            addCriterion("TFMC not in", values, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcBetween(String value1, String value2) {
            addCriterion("TFMC between", value1, value2, "tfmc");
            return (Criteria) this;
        }

        public Criteria andTfmcNotBetween(String value1, String value2) {
            addCriterion("TFMC not between", value1, value2, "tfmc");
            return (Criteria) this;
        }

        public Criteria andBlcIsNull() {
            addCriterion("BLC is null");
            return (Criteria) this;
        }

        public Criteria andBlcIsNotNull() {
            addCriterion("BLC is not null");
            return (Criteria) this;
        }

        public Criteria andBlcEqualTo(String value) {
            addCriterion("BLC =", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcNotEqualTo(String value) {
            addCriterion("BLC <>", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcGreaterThan(String value) {
            addCriterion("BLC >", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcGreaterThanOrEqualTo(String value) {
            addCriterion("BLC >=", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcLessThan(String value) {
            addCriterion("BLC <", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcLessThanOrEqualTo(String value) {
            addCriterion("BLC <=", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcLike(String value) {
            addCriterion("BLC like", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcNotLike(String value) {
            addCriterion("BLC not like", value, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcIn(List<String> values) {
            addCriterion("BLC in", values, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcNotIn(List<String> values) {
            addCriterion("BLC not in", values, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcBetween(String value1, String value2) {
            addCriterion("BLC between", value1, value2, "blc");
            return (Criteria) this;
        }

        public Criteria andBlcNotBetween(String value1, String value2) {
            addCriterion("BLC not between", value1, value2, "blc");
            return (Criteria) this;
        }

        public Criteria andZbxtIsNull() {
            addCriterion("ZBXT is null");
            return (Criteria) this;
        }

        public Criteria andZbxtIsNotNull() {
            addCriterion("ZBXT is not null");
            return (Criteria) this;
        }

        public Criteria andZbxtEqualTo(String value) {
            addCriterion("ZBXT =", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtNotEqualTo(String value) {
            addCriterion("ZBXT <>", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtGreaterThan(String value) {
            addCriterion("ZBXT >", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtGreaterThanOrEqualTo(String value) {
            addCriterion("ZBXT >=", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtLessThan(String value) {
            addCriterion("ZBXT <", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtLessThanOrEqualTo(String value) {
            addCriterion("ZBXT <=", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtLike(String value) {
            addCriterion("ZBXT like", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtNotLike(String value) {
            addCriterion("ZBXT not like", value, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtIn(List<String> values) {
            addCriterion("ZBXT in", values, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtNotIn(List<String> values) {
            addCriterion("ZBXT not in", values, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtBetween(String value1, String value2) {
            addCriterion("ZBXT between", value1, value2, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZbxtNotBetween(String value1, String value2) {
            addCriterion("ZBXT not between", value1, value2, "zbxt");
            return (Criteria) this;
        }

        public Criteria andZjdIsNull() {
            addCriterion("ZJD is null");
            return (Criteria) this;
        }

        public Criteria andZjdIsNotNull() {
            addCriterion("ZJD is not null");
            return (Criteria) this;
        }

        public Criteria andZjdEqualTo(BigDecimal value) {
            addCriterion("ZJD =", value, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdNotEqualTo(BigDecimal value) {
            addCriterion("ZJD <>", value, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdGreaterThan(BigDecimal value) {
            addCriterion("ZJD >", value, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ZJD >=", value, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdLessThan(BigDecimal value) {
            addCriterion("ZJD <", value, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ZJD <=", value, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdIn(List<BigDecimal> values) {
            addCriterion("ZJD in", values, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdNotIn(List<BigDecimal> values) {
            addCriterion("ZJD not in", values, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZJD between", value1, value2, "zjd");
            return (Criteria) this;
        }

        public Criteria andZjdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ZJD not between", value1, value2, "zjd");
            return (Criteria) this;
        }

        public Criteria andYjdIsNull() {
            addCriterion("YJD is null");
            return (Criteria) this;
        }

        public Criteria andYjdIsNotNull() {
            addCriterion("YJD is not null");
            return (Criteria) this;
        }

        public Criteria andYjdEqualTo(BigDecimal value) {
            addCriterion("YJD =", value, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdNotEqualTo(BigDecimal value) {
            addCriterion("YJD <>", value, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdGreaterThan(BigDecimal value) {
            addCriterion("YJD >", value, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("YJD >=", value, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdLessThan(BigDecimal value) {
            addCriterion("YJD <", value, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("YJD <=", value, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdIn(List<BigDecimal> values) {
            addCriterion("YJD in", values, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdNotIn(List<BigDecimal> values) {
            addCriterion("YJD not in", values, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YJD between", value1, value2, "yjd");
            return (Criteria) this;
        }

        public Criteria andYjdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("YJD not between", value1, value2, "yjd");
            return (Criteria) this;
        }

        public Criteria andSwdIsNull() {
            addCriterion("SWD is null");
            return (Criteria) this;
        }

        public Criteria andSwdIsNotNull() {
            addCriterion("SWD is not null");
            return (Criteria) this;
        }

        public Criteria andSwdEqualTo(BigDecimal value) {
            addCriterion("SWD =", value, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdNotEqualTo(BigDecimal value) {
            addCriterion("SWD <>", value, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdGreaterThan(BigDecimal value) {
            addCriterion("SWD >", value, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SWD >=", value, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdLessThan(BigDecimal value) {
            addCriterion("SWD <", value, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SWD <=", value, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdIn(List<BigDecimal> values) {
            addCriterion("SWD in", values, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdNotIn(List<BigDecimal> values) {
            addCriterion("SWD not in", values, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SWD between", value1, value2, "swd");
            return (Criteria) this;
        }

        public Criteria andSwdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SWD not between", value1, value2, "swd");
            return (Criteria) this;
        }

        public Criteria andXwdIsNull() {
            addCriterion("XWD is null");
            return (Criteria) this;
        }

        public Criteria andXwdIsNotNull() {
            addCriterion("XWD is not null");
            return (Criteria) this;
        }

        public Criteria andXwdEqualTo(BigDecimal value) {
            addCriterion("XWD =", value, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdNotEqualTo(BigDecimal value) {
            addCriterion("XWD <>", value, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdGreaterThan(BigDecimal value) {
            addCriterion("XWD >", value, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("XWD >=", value, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdLessThan(BigDecimal value) {
            addCriterion("XWD <", value, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("XWD <=", value, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdIn(List<BigDecimal> values) {
            addCriterion("XWD in", values, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdNotIn(List<BigDecimal> values) {
            addCriterion("XWD not in", values, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XWD between", value1, value2, "xwd");
            return (Criteria) this;
        }

        public Criteria andXwdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XWD not between", value1, value2, "xwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 02 15:45:26 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}