package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class WutanHangkongwutanBck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_hangkongwutan_bck.WT_HKWTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long wtHkwtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_hangkongwutan_bck.X
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_hangkongwutan_bck.Y
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_hangkongwutan_bck.Z
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal z;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_hangkongwutan_bck.DATA
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_hangkongwutan_bck.WTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long wtid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_hangkongwutan_bck.WT_HKWTID
     *
     * @return the value of wutan_hangkongwutan_bck.WT_HKWTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getWtHkwtid() {
        return wtHkwtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_hangkongwutan_bck.WT_HKWTID
     *
     * @param wtHkwtid the value for wutan_hangkongwutan_bck.WT_HKWTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWtHkwtid(Long wtHkwtid) {
        this.wtHkwtid = wtHkwtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_hangkongwutan_bck.X
     *
     * @return the value of wutan_hangkongwutan_bck.X
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_hangkongwutan_bck.X
     *
     * @param x the value for wutan_hangkongwutan_bck.X
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setX(BigDecimal x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_hangkongwutan_bck.Y
     *
     * @return the value of wutan_hangkongwutan_bck.Y
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_hangkongwutan_bck.Y
     *
     * @param y the value for wutan_hangkongwutan_bck.Y
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setY(BigDecimal y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_hangkongwutan_bck.Z
     *
     * @return the value of wutan_hangkongwutan_bck.Z
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZ() {
        return z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_hangkongwutan_bck.Z
     *
     * @param z the value for wutan_hangkongwutan_bck.Z
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZ(BigDecimal z) {
        this.z = z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_hangkongwutan_bck.DATA
     *
     * @return the value of wutan_hangkongwutan_bck.DATA
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_hangkongwutan_bck.DATA
     *
     * @param data the value for wutan_hangkongwutan_bck.DATA
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setData(BigDecimal data) {
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_hangkongwutan_bck.WTID
     *
     * @return the value of wutan_hangkongwutan_bck.WTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getWtid() {
        return wtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_hangkongwutan_bck.WTID
     *
     * @param wtid the value for wutan_hangkongwutan_bck.WTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWtid(Long wtid) {
        this.wtid = wtid;
    }
}