package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class WutanBosuceshiBck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.WT_BSCSID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long wtBscsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.DC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String dc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.SD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.HD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal hd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.DBZS_Tp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal dbzsTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.DBZS_Ts
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal dbzsTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.JDZK_XJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal jdzkXj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.DCBS_Vp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal dcbsVp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.DCBS_Vs
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal dcbsVs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.PJBS_Vp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal pjbsVp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.PJBS_Vs
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal pjbsVs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.Vse
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String vse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutan_bosuceshi_bck.WTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long wtid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.WT_BSCSID
     *
     * @return the value of wutan_bosuceshi_bck.WT_BSCSID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getWtBscsid() {
        return wtBscsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.WT_BSCSID
     *
     * @param wtBscsid the value for wutan_bosuceshi_bck.WT_BSCSID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWtBscsid(Long wtBscsid) {
        this.wtBscsid = wtBscsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.DC
     *
     * @return the value of wutan_bosuceshi_bck.DC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getDc() {
        return dc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.DC
     *
     * @param dc the value for wutan_bosuceshi_bck.DC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDc(String dc) {
        this.dc = dc == null ? null : dc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.SD
     *
     * @return the value of wutan_bosuceshi_bck.SD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getSd() {
        return sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.SD
     *
     * @param sd the value for wutan_bosuceshi_bck.SD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSd(BigDecimal sd) {
        this.sd = sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.HD
     *
     * @return the value of wutan_bosuceshi_bck.HD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getHd() {
        return hd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.HD
     *
     * @param hd the value for wutan_bosuceshi_bck.HD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHd(BigDecimal hd) {
        this.hd = hd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.DBZS_Tp
     *
     * @return the value of wutan_bosuceshi_bck.DBZS_Tp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getDbzsTp() {
        return dbzsTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.DBZS_Tp
     *
     * @param dbzsTp the value for wutan_bosuceshi_bck.DBZS_Tp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDbzsTp(BigDecimal dbzsTp) {
        this.dbzsTp = dbzsTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.DBZS_Ts
     *
     * @return the value of wutan_bosuceshi_bck.DBZS_Ts
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getDbzsTs() {
        return dbzsTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.DBZS_Ts
     *
     * @param dbzsTs the value for wutan_bosuceshi_bck.DBZS_Ts
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDbzsTs(BigDecimal dbzsTs) {
        this.dbzsTs = dbzsTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.JDZK_XJ
     *
     * @return the value of wutan_bosuceshi_bck.JDZK_XJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getJdzkXj() {
        return jdzkXj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.JDZK_XJ
     *
     * @param jdzkXj the value for wutan_bosuceshi_bck.JDZK_XJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setJdzkXj(BigDecimal jdzkXj) {
        this.jdzkXj = jdzkXj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.DCBS_Vp
     *
     * @return the value of wutan_bosuceshi_bck.DCBS_Vp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getDcbsVp() {
        return dcbsVp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.DCBS_Vp
     *
     * @param dcbsVp the value for wutan_bosuceshi_bck.DCBS_Vp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDcbsVp(BigDecimal dcbsVp) {
        this.dcbsVp = dcbsVp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.DCBS_Vs
     *
     * @return the value of wutan_bosuceshi_bck.DCBS_Vs
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getDcbsVs() {
        return dcbsVs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.DCBS_Vs
     *
     * @param dcbsVs the value for wutan_bosuceshi_bck.DCBS_Vs
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDcbsVs(BigDecimal dcbsVs) {
        this.dcbsVs = dcbsVs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.PJBS_Vp
     *
     * @return the value of wutan_bosuceshi_bck.PJBS_Vp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getPjbsVp() {
        return pjbsVp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.PJBS_Vp
     *
     * @param pjbsVp the value for wutan_bosuceshi_bck.PJBS_Vp
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setPjbsVp(BigDecimal pjbsVp) {
        this.pjbsVp = pjbsVp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.PJBS_Vs
     *
     * @return the value of wutan_bosuceshi_bck.PJBS_Vs
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getPjbsVs() {
        return pjbsVs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.PJBS_Vs
     *
     * @param pjbsVs the value for wutan_bosuceshi_bck.PJBS_Vs
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setPjbsVs(BigDecimal pjbsVs) {
        this.pjbsVs = pjbsVs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.Vse
     *
     * @return the value of wutan_bosuceshi_bck.Vse
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getVse() {
        return vse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.Vse
     *
     * @param vse the value for wutan_bosuceshi_bck.Vse
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setVse(String vse) {
        this.vse = vse == null ? null : vse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutan_bosuceshi_bck.WTID
     *
     * @return the value of wutan_bosuceshi_bck.WTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getWtid() {
        return wtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutan_bosuceshi_bck.WTID
     *
     * @param wtid the value for wutan_bosuceshi_bck.WTID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWtid(Long wtid) {
        this.wtid = wtid;
    }
}