package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class WutanduixiangCexianDadidianci {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.WTDX_CX_DDDCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long wtdxCxDddcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.WTDX_CXID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long wtdxCxid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.KCJD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String kcjd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.GDMC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String gdmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.LCFW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal lcfw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.CXH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String cxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.CDH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String cdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZB_N
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zbN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZB_E
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zbE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.GC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal gc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.LC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal lc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZK_Zxx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zkZxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZK_Zxy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zkZxy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZK_Zyx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zkZyx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZK_Zyy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zkZyy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zhhsQzTzx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zhhsQzTzy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.XY_SDZL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal xySdzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.XY_XW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal xyXw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.YX_SDZL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal yxSdzl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.YX_XW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal yxXw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.Z_QZSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zQzsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZXWXZ_TPR
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String zxwxzTpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.ZLJCD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String zljcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.SDZLFY
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String sdzlfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.SM
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String sm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.CCZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String ccz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wutanduixiang_cexian_dadidianci.FHZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String fhz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.WTDX_CX_DDDCID
     *
     * @return the value of wutanduixiang_cexian_dadidianci.WTDX_CX_DDDCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getWtdxCxDddcid() {
        return wtdxCxDddcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.WTDX_CX_DDDCID
     *
     * @param wtdxCxDddcid the value for wutanduixiang_cexian_dadidianci.WTDX_CX_DDDCID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWtdxCxDddcid(Long wtdxCxDddcid) {
        this.wtdxCxDddcid = wtdxCxDddcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.WTDX_CXID
     *
     * @return the value of wutanduixiang_cexian_dadidianci.WTDX_CXID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getWtdxCxid() {
        return wtdxCxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.WTDX_CXID
     *
     * @param wtdxCxid the value for wutanduixiang_cexian_dadidianci.WTDX_CXID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWtdxCxid(Long wtdxCxid) {
        this.wtdxCxid = wtdxCxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.KCJD
     *
     * @return the value of wutanduixiang_cexian_dadidianci.KCJD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getKcjd() {
        return kcjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.KCJD
     *
     * @param kcjd the value for wutanduixiang_cexian_dadidianci.KCJD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setKcjd(String kcjd) {
        this.kcjd = kcjd == null ? null : kcjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.GDMC
     *
     * @return the value of wutanduixiang_cexian_dadidianci.GDMC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getGdmc() {
        return gdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.GDMC
     *
     * @param gdmc the value for wutanduixiang_cexian_dadidianci.GDMC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setGdmc(String gdmc) {
        this.gdmc = gdmc == null ? null : gdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.LCFW
     *
     * @return the value of wutanduixiang_cexian_dadidianci.LCFW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getLcfw() {
        return lcfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.LCFW
     *
     * @param lcfw the value for wutanduixiang_cexian_dadidianci.LCFW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setLcfw(BigDecimal lcfw) {
        this.lcfw = lcfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.CXH
     *
     * @return the value of wutanduixiang_cexian_dadidianci.CXH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getCxh() {
        return cxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.CXH
     *
     * @param cxh the value for wutanduixiang_cexian_dadidianci.CXH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setCxh(String cxh) {
        this.cxh = cxh == null ? null : cxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.CDH
     *
     * @return the value of wutanduixiang_cexian_dadidianci.CDH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getCdh() {
        return cdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.CDH
     *
     * @param cdh the value for wutanduixiang_cexian_dadidianci.CDH
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setCdh(String cdh) {
        this.cdh = cdh == null ? null : cdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZB_N
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZB_N
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZbN() {
        return zbN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZB_N
     *
     * @param zbN the value for wutanduixiang_cexian_dadidianci.ZB_N
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZbN(BigDecimal zbN) {
        this.zbN = zbN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZB_E
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZB_E
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZbE() {
        return zbE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZB_E
     *
     * @param zbE the value for wutanduixiang_cexian_dadidianci.ZB_E
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZbE(BigDecimal zbE) {
        this.zbE = zbE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.GC
     *
     * @return the value of wutanduixiang_cexian_dadidianci.GC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getGc() {
        return gc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.GC
     *
     * @param gc the value for wutanduixiang_cexian_dadidianci.GC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setGc(BigDecimal gc) {
        this.gc = gc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.LC
     *
     * @return the value of wutanduixiang_cexian_dadidianci.LC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getLc() {
        return lc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.LC
     *
     * @param lc the value for wutanduixiang_cexian_dadidianci.LC
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setLc(BigDecimal lc) {
        this.lc = lc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zxx
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZK_Zxx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZkZxx() {
        return zkZxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zxx
     *
     * @param zkZxx the value for wutanduixiang_cexian_dadidianci.ZK_Zxx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZkZxx(BigDecimal zkZxx) {
        this.zkZxx = zkZxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zxy
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZK_Zxy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZkZxy() {
        return zkZxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zxy
     *
     * @param zkZxy the value for wutanduixiang_cexian_dadidianci.ZK_Zxy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZkZxy(BigDecimal zkZxy) {
        this.zkZxy = zkZxy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zyx
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZK_Zyx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZkZyx() {
        return zkZyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zyx
     *
     * @param zkZyx the value for wutanduixiang_cexian_dadidianci.ZK_Zyx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZkZyx(BigDecimal zkZyx) {
        this.zkZyx = zkZyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zyy
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZK_Zyy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZkZyy() {
        return zkZyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZK_Zyy
     *
     * @param zkZyy the value for wutanduixiang_cexian_dadidianci.ZK_Zyy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZkZyy(BigDecimal zkZyy) {
        this.zkZyy = zkZyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzx
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZhhsQzTzx() {
        return zhhsQzTzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzx
     *
     * @param zhhsQzTzx the value for wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzx
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZhhsQzTzx(BigDecimal zhhsQzTzx) {
        this.zhhsQzTzx = zhhsQzTzx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzy
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZhhsQzTzy() {
        return zhhsQzTzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzy
     *
     * @param zhhsQzTzy the value for wutanduixiang_cexian_dadidianci.ZHHS_QZ_Tzy
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZhhsQzTzy(BigDecimal zhhsQzTzy) {
        this.zhhsQzTzy = zhhsQzTzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.XY_SDZL
     *
     * @return the value of wutanduixiang_cexian_dadidianci.XY_SDZL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getXySdzl() {
        return xySdzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.XY_SDZL
     *
     * @param xySdzl the value for wutanduixiang_cexian_dadidianci.XY_SDZL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXySdzl(BigDecimal xySdzl) {
        this.xySdzl = xySdzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.XY_XW
     *
     * @return the value of wutanduixiang_cexian_dadidianci.XY_XW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getXyXw() {
        return xyXw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.XY_XW
     *
     * @param xyXw the value for wutanduixiang_cexian_dadidianci.XY_XW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setXyXw(BigDecimal xyXw) {
        this.xyXw = xyXw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.YX_SDZL
     *
     * @return the value of wutanduixiang_cexian_dadidianci.YX_SDZL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getYxSdzl() {
        return yxSdzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.YX_SDZL
     *
     * @param yxSdzl the value for wutanduixiang_cexian_dadidianci.YX_SDZL
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setYxSdzl(BigDecimal yxSdzl) {
        this.yxSdzl = yxSdzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.YX_XW
     *
     * @return the value of wutanduixiang_cexian_dadidianci.YX_XW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getYxXw() {
        return yxXw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.YX_XW
     *
     * @param yxXw the value for wutanduixiang_cexian_dadidianci.YX_XW
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setYxXw(BigDecimal yxXw) {
        this.yxXw = yxXw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.Z_QZSD
     *
     * @return the value of wutanduixiang_cexian_dadidianci.Z_QZSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getzQzsd() {
        return zQzsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.Z_QZSD
     *
     * @param zQzsd the value for wutanduixiang_cexian_dadidianci.Z_QZSD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setzQzsd(BigDecimal zQzsd) {
        this.zQzsd = zQzsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZXWXZ_TPR
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZXWXZ_TPR
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getZxwxzTpr() {
        return zxwxzTpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZXWXZ_TPR
     *
     * @param zxwxzTpr the value for wutanduixiang_cexian_dadidianci.ZXWXZ_TPR
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZxwxzTpr(String zxwxzTpr) {
        this.zxwxzTpr = zxwxzTpr == null ? null : zxwxzTpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.ZLJCD
     *
     * @return the value of wutanduixiang_cexian_dadidianci.ZLJCD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getZljcd() {
        return zljcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.ZLJCD
     *
     * @param zljcd the value for wutanduixiang_cexian_dadidianci.ZLJCD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZljcd(String zljcd) {
        this.zljcd = zljcd == null ? null : zljcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.SDZLFY
     *
     * @return the value of wutanduixiang_cexian_dadidianci.SDZLFY
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getSdzlfy() {
        return sdzlfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.SDZLFY
     *
     * @param sdzlfy the value for wutanduixiang_cexian_dadidianci.SDZLFY
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSdzlfy(String sdzlfy) {
        this.sdzlfy = sdzlfy == null ? null : sdzlfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.SM
     *
     * @return the value of wutanduixiang_cexian_dadidianci.SM
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getSm() {
        return sm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.SM
     *
     * @param sm the value for wutanduixiang_cexian_dadidianci.SM
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setSm(String sm) {
        this.sm = sm == null ? null : sm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.CCZ
     *
     * @return the value of wutanduixiang_cexian_dadidianci.CCZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getCcz() {
        return ccz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.CCZ
     *
     * @param ccz the value for wutanduixiang_cexian_dadidianci.CCZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setCcz(String ccz) {
        this.ccz = ccz == null ? null : ccz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wutanduixiang_cexian_dadidianci.FHZ
     *
     * @return the value of wutanduixiang_cexian_dadidianci.FHZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getFhz() {
        return fhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wutanduixiang_cexian_dadidianci.FHZ
     *
     * @param fhz the value for wutanduixiang_cexian_dadidianci.FHZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setFhz(String fhz) {
        this.fhz = fhz == null ? null : fhz.trim();
    }
}