package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class YaoganJieyichengguoBuliangdizhiHuapocuoluo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZ_HPCLID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long ygJycgBldzHpclid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long ygJycgBldzid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_N
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zbN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_E
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zbE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.LX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String lx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.HDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String hdfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.CD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal cd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.PJKD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal pjkd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.MJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal mj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.WZCF
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String wzcf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YFYS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String yfys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZ_HPCLID
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZ_HPCLID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getYgJycgBldzHpclid() {
        return ygJycgBldzHpclid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZ_HPCLID
     *
     * @param ygJycgBldzHpclid the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZ_HPCLID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setYgJycgBldzHpclid(Long ygJycgBldzHpclid) {
        this.ygJycgBldzHpclid = ygJycgBldzHpclid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZID
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getYgJycgBldzid() {
        return ygJycgBldzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZID
     *
     * @param ygJycgBldzid the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YG_JYCG_BLDZID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setYgJycgBldzid(Long ygJycgBldzid) {
        this.ygJycgBldzid = ygJycgBldzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_N
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_N
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZbN() {
        return zbN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_N
     *
     * @param zbN the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_N
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZbN(BigDecimal zbN) {
        this.zbN = zbN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_E
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_E
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZbE() {
        return zbE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_E
     *
     * @param zbE the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.ZB_E
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZbE(BigDecimal zbE) {
        this.zbE = zbE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.LX
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.LX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.LX
     *
     * @param lx the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.LX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.HDFX
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.HDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getHdfx() {
        return hdfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.HDFX
     *
     * @param hdfx the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.HDFX
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setHdfx(String hdfx) {
        this.hdfx = hdfx == null ? null : hdfx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.CD
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.CD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getCd() {
        return cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.CD
     *
     * @param cd the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.CD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setCd(BigDecimal cd) {
        this.cd = cd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.PJKD
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.PJKD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getPjkd() {
        return pjkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.PJKD
     *
     * @param pjkd the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.PJKD
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setPjkd(BigDecimal pjkd) {
        this.pjkd = pjkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.MJ
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.MJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getMj() {
        return mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.MJ
     *
     * @param mj the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.MJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setMj(BigDecimal mj) {
        this.mj = mj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.WZCF
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.WZCF
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getWzcf() {
        return wzcf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.WZCF
     *
     * @param wzcf the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.WZCF
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setWzcf(String wzcf) {
        this.wzcf = wzcf == null ? null : wzcf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YFYS
     *
     * @return the value of yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YFYS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getYfys() {
        return yfys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YFYS
     *
     * @param yfys the value for yaogan_jieyichengguo_buliangdizhi_huapocuoluo.YFYS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setYfys(String yfys) {
        this.yfys = yfys == null ? null : yfys.trim();
    }
}