package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ZuankongyuanweiceshiShuiwenceshiYashuishiyanshuiweiguancejiluExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public ZuankongyuanweiceshiShuiwenceshiYashuishiyanshuiweiguancejiluExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZkywcsSwcsYssyswgcjlidIsNull() {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID is null");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidIsNotNull() {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID is not null");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID =", value, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidNotEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID <>", value, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidGreaterThan(Long value) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID >", value, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidGreaterThanOrEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID >=", value, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidLessThan(Long value) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID <", value, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidLessThanOrEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID <=", value, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidIn(List<Long> values) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID in", values, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidNotIn(List<Long> values) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID not in", values, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidBetween(Long value1, Long value2) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID between", value1, value2, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsYssyswgcjlidNotBetween(Long value1, Long value2) {
            addCriterion("ZKYWCS_SWCS_YSSYSWGCJLID not between", value1, value2, "zkywcsSwcsYssyswgcjlid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidIsNull() {
            addCriterion("ZKYWCS_SWCSID is null");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidIsNotNull() {
            addCriterion("ZKYWCS_SWCSID is not null");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCSID =", value, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidNotEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCSID <>", value, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidGreaterThan(Long value) {
            addCriterion("ZKYWCS_SWCSID >", value, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidGreaterThanOrEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCSID >=", value, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidLessThan(Long value) {
            addCriterion("ZKYWCS_SWCSID <", value, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidLessThanOrEqualTo(Long value) {
            addCriterion("ZKYWCS_SWCSID <=", value, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidIn(List<Long> values) {
            addCriterion("ZKYWCS_SWCSID in", values, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidNotIn(List<Long> values) {
            addCriterion("ZKYWCS_SWCSID not in", values, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidBetween(Long value1, Long value2) {
            addCriterion("ZKYWCS_SWCSID between", value1, value2, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andZkywcsSwcsidNotBetween(Long value1, Long value2) {
            addCriterion("ZKYWCS_SWCSID not between", value1, value2, "zkywcsSwcsid");
            return (Criteria) this;
        }

        public Criteria andSybhIsNull() {
            addCriterion("SYBH is null");
            return (Criteria) this;
        }

        public Criteria andSybhIsNotNull() {
            addCriterion("SYBH is not null");
            return (Criteria) this;
        }

        public Criteria andSybhEqualTo(String value) {
            addCriterion("SYBH =", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhNotEqualTo(String value) {
            addCriterion("SYBH <>", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhGreaterThan(String value) {
            addCriterion("SYBH >", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhGreaterThanOrEqualTo(String value) {
            addCriterion("SYBH >=", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhLessThan(String value) {
            addCriterion("SYBH <", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhLessThanOrEqualTo(String value) {
            addCriterion("SYBH <=", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhLike(String value) {
            addCriterion("SYBH like", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhNotLike(String value) {
            addCriterion("SYBH not like", value, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhIn(List<String> values) {
            addCriterion("SYBH in", values, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhNotIn(List<String> values) {
            addCriterion("SYBH not in", values, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhBetween(String value1, String value2) {
            addCriterion("SYBH between", value1, value2, "sybh");
            return (Criteria) this;
        }

        public Criteria andSybhNotBetween(String value1, String value2) {
            addCriterion("SYBH not between", value1, value2, "sybh");
            return (Criteria) this;
        }

        public Criteria andTimeHIsNull() {
            addCriterion("TIME_H is null");
            return (Criteria) this;
        }

        public Criteria andTimeHIsNotNull() {
            addCriterion("TIME_H is not null");
            return (Criteria) this;
        }

        public Criteria andTimeHEqualTo(String value) {
            addCriterion("TIME_H =", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHNotEqualTo(String value) {
            addCriterion("TIME_H <>", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHGreaterThan(String value) {
            addCriterion("TIME_H >", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHGreaterThanOrEqualTo(String value) {
            addCriterion("TIME_H >=", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHLessThan(String value) {
            addCriterion("TIME_H <", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHLessThanOrEqualTo(String value) {
            addCriterion("TIME_H <=", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHLike(String value) {
            addCriterion("TIME_H like", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHNotLike(String value) {
            addCriterion("TIME_H not like", value, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHIn(List<String> values) {
            addCriterion("TIME_H in", values, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHNotIn(List<String> values) {
            addCriterion("TIME_H not in", values, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHBetween(String value1, String value2) {
            addCriterion("TIME_H between", value1, value2, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeHNotBetween(String value1, String value2) {
            addCriterion("TIME_H not between", value1, value2, "timeH");
            return (Criteria) this;
        }

        public Criteria andTimeMIsNull() {
            addCriterion("TIME_M is null");
            return (Criteria) this;
        }

        public Criteria andTimeMIsNotNull() {
            addCriterion("TIME_M is not null");
            return (Criteria) this;
        }

        public Criteria andTimeMEqualTo(String value) {
            addCriterion("TIME_M =", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMNotEqualTo(String value) {
            addCriterion("TIME_M <>", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMGreaterThan(String value) {
            addCriterion("TIME_M >", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMGreaterThanOrEqualTo(String value) {
            addCriterion("TIME_M >=", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMLessThan(String value) {
            addCriterion("TIME_M <", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMLessThanOrEqualTo(String value) {
            addCriterion("TIME_M <=", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMLike(String value) {
            addCriterion("TIME_M like", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMNotLike(String value) {
            addCriterion("TIME_M not like", value, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMIn(List<String> values) {
            addCriterion("TIME_M in", values, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMNotIn(List<String> values) {
            addCriterion("TIME_M not in", values, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMBetween(String value1, String value2) {
            addCriterion("TIME_M between", value1, value2, "timeM");
            return (Criteria) this;
        }

        public Criteria andTimeMNotBetween(String value1, String value2) {
            addCriterion("TIME_M not between", value1, value2, "timeM");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdIsNull() {
            addCriterion("GCDZSWSD is null");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdIsNotNull() {
            addCriterion("GCDZSWSD is not null");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdEqualTo(BigDecimal value) {
            addCriterion("GCDZSWSD =", value, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdNotEqualTo(BigDecimal value) {
            addCriterion("GCDZSWSD <>", value, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdGreaterThan(BigDecimal value) {
            addCriterion("GCDZSWSD >", value, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GCDZSWSD >=", value, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdLessThan(BigDecimal value) {
            addCriterion("GCDZSWSD <", value, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GCDZSWSD <=", value, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdIn(List<BigDecimal> values) {
            addCriterion("GCDZSWSD in", values, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdNotIn(List<BigDecimal> values) {
            addCriterion("GCDZSWSD not in", values, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GCDZSWSD between", value1, value2, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdzswsdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GCDZSWSD not between", value1, value2, "gcdzswsd");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmIsNull() {
            addCriterion("GCDGCDM is null");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmIsNotNull() {
            addCriterion("GCDGCDM is not null");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmEqualTo(BigDecimal value) {
            addCriterion("GCDGCDM =", value, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmNotEqualTo(BigDecimal value) {
            addCriterion("GCDGCDM <>", value, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmGreaterThan(BigDecimal value) {
            addCriterion("GCDGCDM >", value, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GCDGCDM >=", value, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmLessThan(BigDecimal value) {
            addCriterion("GCDGCDM <", value, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GCDGCDM <=", value, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmIn(List<BigDecimal> values) {
            addCriterion("GCDGCDM in", values, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmNotIn(List<BigDecimal> values) {
            addCriterion("GCDGCDM not in", values, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GCDGCDM between", value1, value2, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andGcdgcdmNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GCDGCDM not between", value1, value2, "gcdgcdm");
            return (Criteria) this;
        }

        public Criteria andDmzswsdIsNull() {
            addCriterion("DMZSWSD is null");
            return (Criteria) this;
        }

        public Criteria andDmzswsdIsNotNull() {
            addCriterion("DMZSWSD is not null");
            return (Criteria) this;
        }

        public Criteria andDmzswsdEqualTo(BigDecimal value) {
            addCriterion("DMZSWSD =", value, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdNotEqualTo(BigDecimal value) {
            addCriterion("DMZSWSD <>", value, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdGreaterThan(BigDecimal value) {
            addCriterion("DMZSWSD >", value, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DMZSWSD >=", value, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdLessThan(BigDecimal value) {
            addCriterion("DMZSWSD <", value, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DMZSWSD <=", value, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdIn(List<BigDecimal> values) {
            addCriterion("DMZSWSD in", values, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdNotIn(List<BigDecimal> values) {
            addCriterion("DMZSWSD not in", values, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DMZSWSD between", value1, value2, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andDmzswsdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DMZSWSD not between", value1, value2, "dmzswsd");
            return (Criteria) this;
        }

        public Criteria andBzIsNull() {
            addCriterion("BZ is null");
            return (Criteria) this;
        }

        public Criteria andBzIsNotNull() {
            addCriterion("BZ is not null");
            return (Criteria) this;
        }

        public Criteria andBzEqualTo(String value) {
            addCriterion("BZ =", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotEqualTo(String value) {
            addCriterion("BZ <>", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThan(String value) {
            addCriterion("BZ >", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzGreaterThanOrEqualTo(String value) {
            addCriterion("BZ >=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThan(String value) {
            addCriterion("BZ <", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLessThanOrEqualTo(String value) {
            addCriterion("BZ <=", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzLike(String value) {
            addCriterion("BZ like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotLike(String value) {
            addCriterion("BZ not like", value, "bz");
            return (Criteria) this;
        }

        public Criteria andBzIn(List<String> values) {
            addCriterion("BZ in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotIn(List<String> values) {
            addCriterion("BZ not in", values, "bz");
            return (Criteria) this;
        }

        public Criteria andBzBetween(String value1, String value2) {
            addCriterion("BZ between", value1, value2, "bz");
            return (Criteria) this;
        }

        public Criteria andBzNotBetween(String value1, String value2) {
            addCriterion("BZ not between", value1, value2, "bz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 02 15:45:26 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_yashuishiyanshuiweiguancejilu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}