package cn.xjtu.zun.tiesheyuan.pojo;

import java.math.BigDecimal;

public class ZuantanyujianyikantanZuankongkongjing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuantanyujianyikantan_zuankongkongjing.ZTYJYKT_ZKKJID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long ztyjyktZkkjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuantanyujianyikantan_zuankongkongjing.ZKID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private Long zkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuantanyujianyikantan_zuankongkongjing.QSKS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal qsks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuantanyujianyikantan_zuankongkongjing.ZKKJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private BigDecimal zkkj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zuantanyujianyikantan_zuankongkongjing.BZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    private String bz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuantanyujianyikantan_zuankongkongjing.ZTYJYKT_ZKKJID
     *
     * @return the value of zuantanyujianyikantan_zuankongkongjing.ZTYJYKT_ZKKJID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getZtyjyktZkkjid() {
        return ztyjyktZkkjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuantanyujianyikantan_zuankongkongjing.ZTYJYKT_ZKKJID
     *
     * @param ztyjyktZkkjid the value for zuantanyujianyikantan_zuankongkongjing.ZTYJYKT_ZKKJID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZtyjyktZkkjid(Long ztyjyktZkkjid) {
        this.ztyjyktZkkjid = ztyjyktZkkjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuantanyujianyikantan_zuankongkongjing.ZKID
     *
     * @return the value of zuantanyujianyikantan_zuankongkongjing.ZKID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public Long getZkid() {
        return zkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuantanyujianyikantan_zuankongkongjing.ZKID
     *
     * @param zkid the value for zuantanyujianyikantan_zuankongkongjing.ZKID
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZkid(Long zkid) {
        this.zkid = zkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuantanyujianyikantan_zuankongkongjing.QSKS
     *
     * @return the value of zuantanyujianyikantan_zuankongkongjing.QSKS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getQsks() {
        return qsks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuantanyujianyikantan_zuankongkongjing.QSKS
     *
     * @param qsks the value for zuantanyujianyikantan_zuankongkongjing.QSKS
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setQsks(BigDecimal qsks) {
        this.qsks = qsks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuantanyujianyikantan_zuankongkongjing.ZKKJ
     *
     * @return the value of zuantanyujianyikantan_zuankongkongjing.ZKKJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public BigDecimal getZkkj() {
        return zkkj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuantanyujianyikantan_zuankongkongjing.ZKKJ
     *
     * @param zkkj the value for zuantanyujianyikantan_zuankongkongjing.ZKKJ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setZkkj(BigDecimal zkkj) {
        this.zkkj = zkkj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zuantanyujianyikantan_zuankongkongjing.BZ
     *
     * @return the value of zuantanyujianyikantan_zuankongkongjing.BZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zuantanyujianyikantan_zuankongkongjing.BZ
     *
     * @param bz the value for zuantanyujianyikantan_zuankongkongjing.BZ
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }
}