package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.Cihualv;
import cn.xjtu.zun.tiesheyuan.pojo.CihualvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CihualvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(CihualvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(CihualvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(Cihualv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(Cihualv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<Cihualv> selectByExample(CihualvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    Cihualv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") Cihualv record, @Param("example") CihualvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") Cihualv record, @Param("example") CihualvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(Cihualv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cihualv
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(Cihualv record);
}