package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.DizhidiaohuiBuliangdizhiHuapo;
import cn.xjtu.zun.tiesheyuan.pojo.DizhidiaohuiBuliangdizhiHuapoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DizhidiaohuiBuliangdizhiHuapoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    long countByExample(DizhidiaohuiBuliangdizhiHuapoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int deleteByExample(DizhidiaohuiBuliangdizhiHuapoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int deleteByPrimaryKey(Long dzdhBldzHpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int insert(DizhidiaohuiBuliangdizhiHuapo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int insertSelective(DizhidiaohuiBuliangdizhiHuapo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    List<DizhidiaohuiBuliangdizhiHuapo> selectByExample(DizhidiaohuiBuliangdizhiHuapoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    DizhidiaohuiBuliangdizhiHuapo selectByPrimaryKey(Long dzdhBldzHpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int updateByExampleSelective(@Param("record") DizhidiaohuiBuliangdizhiHuapo record, @Param("example") DizhidiaohuiBuliangdizhiHuapoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int updateByExample(@Param("record") DizhidiaohuiBuliangdizhiHuapo record, @Param("example") DizhidiaohuiBuliangdizhiHuapoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int updateByPrimaryKeySelective(DizhidiaohuiBuliangdizhiHuapo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_buliangdizhi_huapo
     *
     * @mbg.generated Wed Aug 02 15:45:25 CST 2023
     */
    int updateByPrimaryKey(DizhidiaohuiBuliangdizhiHuapo record);
}