package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.DizhidiaohuiDizhigouzaoZhezhou;
import cn.xjtu.zun.tiesheyuan.pojo.DizhidiaohuiDizhigouzaoZhezhouExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DizhidiaohuiDizhigouzaoZhezhouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(DizhidiaohuiDizhigouzaoZhezhouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(DizhidiaohuiDizhigouzaoZhezhouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long dzdhDzgzZzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(DizhidiaohuiDizhigouzaoZhezhou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(DizhidiaohuiDizhigouzaoZhezhou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<DizhidiaohuiDizhigouzaoZhezhou> selectByExample(DizhidiaohuiDizhigouzaoZhezhouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    DizhidiaohuiDizhigouzaoZhezhou selectByPrimaryKey(Long dzdhDzgzZzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") DizhidiaohuiDizhigouzaoZhezhou record, @Param("example") DizhidiaohuiDizhigouzaoZhezhouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") DizhidiaohuiDizhigouzaoZhezhou record, @Param("example") DizhidiaohuiDizhigouzaoZhezhouExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(DizhidiaohuiDizhigouzaoZhezhou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dizhidiaohui_dizhigouzao_zhezhou
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(DizhidiaohuiDizhigouzaoZhezhou record);
}