package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.GaomidudianfaGaomidushujuchengtao;
import cn.xjtu.zun.tiesheyuan.pojo.GaomidudianfaGaomidushujuchengtaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GaomidudianfaGaomidushujuchengtaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(GaomidudianfaGaomidushujuchengtaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(GaomidudianfaGaomidushujuchengtaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(GaomidudianfaGaomidushujuchengtao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(GaomidudianfaGaomidushujuchengtao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<GaomidudianfaGaomidushujuchengtao> selectByExample(GaomidudianfaGaomidushujuchengtaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    GaomidudianfaGaomidushujuchengtao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") GaomidudianfaGaomidushujuchengtao record, @Param("example") GaomidudianfaGaomidushujuchengtaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") GaomidudianfaGaomidushujuchengtao record, @Param("example") GaomidudianfaGaomidushujuchengtaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(GaomidudianfaGaomidushujuchengtao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaomidudianfa_gaomidushujuchengtao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(GaomidudianfaGaomidushujuchengtao record);
}