package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.KantanshujuYanweiceshi;
import cn.xjtu.zun.tiesheyuan.pojo.KantanshujuYanweiceshiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KantanshujuYanweiceshiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(KantanshujuYanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(KantanshujuYanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(KantanshujuYanweiceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(KantanshujuYanweiceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<KantanshujuYanweiceshi> selectByExample(KantanshujuYanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    KantanshujuYanweiceshi selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") KantanshujuYanweiceshi record, @Param("example") KantanshujuYanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") KantanshujuYanweiceshi record, @Param("example") KantanshujuYanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(KantanshujuYanweiceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kantanshuju_yanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(KantanshujuYanweiceshi record);
}