package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanShuizhiquanfenxi;
import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanShuizhiquanfenxiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShineishiyanShuizhiquanfenxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ShineishiyanShuizhiquanfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ShineishiyanShuizhiquanfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long snsySzqfxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(ShineishiyanShuizhiquanfenxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(ShineishiyanShuizhiquanfenxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<ShineishiyanShuizhiquanfenxi> selectByExample(ShineishiyanShuizhiquanfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    ShineishiyanShuizhiquanfenxi selectByPrimaryKey(Long snsySzqfxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") ShineishiyanShuizhiquanfenxi record, @Param("example") ShineishiyanShuizhiquanfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") ShineishiyanShuizhiquanfenxi record, @Param("example") ShineishiyanShuizhiquanfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(ShineishiyanShuizhiquanfenxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhiquanfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(ShineishiyanShuizhiquanfenxi record);
}