package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.WutanduixiangCexian;
import cn.xjtu.zun.tiesheyuan.pojo.WutanduixiangCexianExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WutanduixiangCexianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(WutanduixiangCexianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(WutanduixiangCexianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long wtdxCxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(WutanduixiangCexian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(WutanduixiangCexian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<WutanduixiangCexian> selectByExample(WutanduixiangCexianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    WutanduixiangCexian selectByPrimaryKey(Long wtdxCxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") WutanduixiangCexian record, @Param("example") WutanduixiangCexianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") WutanduixiangCexian record, @Param("example") WutanduixiangCexianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(WutanduixiangCexian record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_cexian
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(WutanduixiangCexian record);
}