package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.WutanduixiangZonghecejing;
import cn.xjtu.zun.tiesheyuan.pojo.WutanduixiangZonghecejingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WutanduixiangZonghecejingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(WutanduixiangZonghecejingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(WutanduixiangZonghecejingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long wtdxZhcjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(WutanduixiangZonghecejing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(WutanduixiangZonghecejing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<WutanduixiangZonghecejing> selectByExample(WutanduixiangZonghecejingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    WutanduixiangZonghecejing selectByPrimaryKey(Long wtdxZhcjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") WutanduixiangZonghecejing record, @Param("example") WutanduixiangZonghecejingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") WutanduixiangZonghecejing record, @Param("example") WutanduixiangZonghecejingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(WutanduixiangZonghecejing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(WutanduixiangZonghecejing record);
}