package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.YaoganJieyichengguoBuliangdizhi;
import cn.xjtu.zun.tiesheyuan.pojo.YaoganJieyichengguoBuliangdizhiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YaoganJieyichengguoBuliangdizhiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(YaoganJieyichengguoBuliangdizhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(YaoganJieyichengguoBuliangdizhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long ygJycgBldzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(YaoganJieyichengguoBuliangdizhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(YaoganJieyichengguoBuliangdizhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<YaoganJieyichengguoBuliangdizhi> selectByExample(YaoganJieyichengguoBuliangdizhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    YaoganJieyichengguoBuliangdizhi selectByPrimaryKey(Long ygJycgBldzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") YaoganJieyichengguoBuliangdizhi record, @Param("example") YaoganJieyichengguoBuliangdizhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") YaoganJieyichengguoBuliangdizhi record, @Param("example") YaoganJieyichengguoBuliangdizhiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(YaoganJieyichengguoBuliangdizhi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_jieyichengguo_buliangdizhi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(YaoganJieyichengguoBuliangdizhi record);
}