package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.YaoganYuanshishuju;
import cn.xjtu.zun.tiesheyuan.pojo.YaoganYuanshishujuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YaoganYuanshishujuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(YaoganYuanshishujuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(YaoganYuanshishujuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long ygYssjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(YaoganYuanshishuju record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(YaoganYuanshishuju record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<YaoganYuanshishuju> selectByExample(YaoganYuanshishujuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    YaoganYuanshishuju selectByPrimaryKey(Long ygYssjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") YaoganYuanshishuju record, @Param("example") YaoganYuanshishujuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") YaoganYuanshishuju record, @Param("example") YaoganYuanshishujuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(YaoganYuanshishuju record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaogan_yuanshishuju
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(YaoganYuanshishuju record);
}