package cn.xjtu.zun.tiesheyuan.mapperImpl;

import cn.xjtu.zun.tiesheyuan.pojo.ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu;
import cn.xjtu.zun.tiesheyuan.pojo.ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long zkywcsSwcsCssyswhfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu> selectByExample(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu selectByPrimaryKey(Long zkywcsSwcsCssyswhfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu record, @Param("example") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu record, @Param("example") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanshuiweihuifu
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanshuiweihuifu record);
}