package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.Feizuankongyuanweiceshi;
import cn.xjtu.zun.tiesheyuan.pojo.FeizuankongyuanweiceshiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeizuankongyuanweiceshiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(FeizuankongyuanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(FeizuankongyuanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long fzkywcsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(Feizuankongyuanweiceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(Feizuankongyuanweiceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<Feizuankongyuanweiceshi> selectByExample(FeizuankongyuanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    Feizuankongyuanweiceshi selectByPrimaryKey(Long fzkywcsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") Feizuankongyuanweiceshi record, @Param("example") FeizuankongyuanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") Feizuankongyuanweiceshi record, @Param("example") FeizuankongyuanweiceshiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(Feizuankongyuanweiceshi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feizuankongyuanweiceshi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(Feizuankongyuanweiceshi record);
}