package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.JichuziliaoXianluxiantiao;
import cn.xjtu.zun.tiesheyuan.pojo.JichuziliaoXianluxiantiaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JichuziliaoXianluxiantiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(JichuziliaoXianluxiantiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(JichuziliaoXianluxiantiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(JichuziliaoXianluxiantiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(JichuziliaoXianluxiantiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<JichuziliaoXianluxiantiao> selectByExample(JichuziliaoXianluxiantiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    JichuziliaoXianluxiantiao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") JichuziliaoXianluxiantiao record, @Param("example") JichuziliaoXianluxiantiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") JichuziliaoXianluxiantiao record, @Param("example") JichuziliaoXianluxiantiaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(JichuziliaoXianluxiantiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_xianluxiantiao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(JichuziliaoXianluxiantiao record);
}