package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.JichuziliaoQuyudizhiziliao;
import cn.xjtu.zun.tiesheyuan.pojo.JichuziliaoQuyudizhiziliaoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JichuziliaoQuyudizhiziliaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(JichuziliaoQuyudizhiziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(JichuziliaoQuyudizhiziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(JichuziliaoQuyudizhiziliao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(JichuziliaoQuyudizhiziliao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<JichuziliaoQuyudizhiziliao> selectByExample(JichuziliaoQuyudizhiziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    JichuziliaoQuyudizhiziliao selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") JichuziliaoQuyudizhiziliao record, @Param("example") JichuziliaoQuyudizhiziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") JichuziliaoQuyudizhiziliao record, @Param("example") JichuziliaoQuyudizhiziliaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(JichuziliaoQuyudizhiziliao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jichuziliao_quyudizhiziliao
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(JichuziliaoQuyudizhiziliao record);
}