package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanShuizhijianfenxi;
import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanShuizhijianfenxiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShineishiyanShuizhijianfenxiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ShineishiyanShuizhijianfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ShineishiyanShuizhijianfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long snsySzjfxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(ShineishiyanShuizhijianfenxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(ShineishiyanShuizhijianfenxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<ShineishiyanShuizhijianfenxi> selectByExample(ShineishiyanShuizhijianfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    ShineishiyanShuizhijianfenxi selectByPrimaryKey(Long snsySzjfxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") ShineishiyanShuizhijianfenxi record, @Param("example") ShineishiyanShuizhijianfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") ShineishiyanShuizhijianfenxi record, @Param("example") ShineishiyanShuizhijianfenxiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(ShineishiyanShuizhijianfenxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_shuizhijianfenxi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(ShineishiyanShuizhijianfenxi record);
}