package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanTugongshiyan;
import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanTugongshiyanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShineishiyanTugongshiyanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ShineishiyanTugongshiyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ShineishiyanTugongshiyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long snsyTgsyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(ShineishiyanTugongshiyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(ShineishiyanTugongshiyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<ShineishiyanTugongshiyan> selectByExample(ShineishiyanTugongshiyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    ShineishiyanTugongshiyan selectByPrimaryKey(Long snsyTgsyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") ShineishiyanTugongshiyan record, @Param("example") ShineishiyanTugongshiyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") ShineishiyanTugongshiyan record, @Param("example") ShineishiyanTugongshiyanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(ShineishiyanTugongshiyan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_tugongshiyan
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(ShineishiyanTugongshiyan record);
}