package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanYanshibaopianjianding;
import cn.xjtu.zun.tiesheyuan.pojo.ShineishiyanYanshibaopianjiandingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShineishiyanYanshibaopianjiandingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ShineishiyanYanshibaopianjiandingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ShineishiyanYanshibaopianjiandingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long snsyYsbpjdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(ShineishiyanYanshibaopianjianding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(ShineishiyanYanshibaopianjianding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<ShineishiyanYanshibaopianjianding> selectByExample(ShineishiyanYanshibaopianjiandingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    ShineishiyanYanshibaopianjianding selectByPrimaryKey(Long snsyYsbpjdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") ShineishiyanYanshibaopianjianding record, @Param("example") ShineishiyanYanshibaopianjiandingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") ShineishiyanYanshibaopianjianding record, @Param("example") ShineishiyanYanshibaopianjiandingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(ShineishiyanYanshibaopianjianding record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineishiyan_yanshibaopianjianding
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(ShineishiyanYanshibaopianjianding record);
}