package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.WutanduixiangZonghecejingFangshexing;
import cn.xjtu.zun.tiesheyuan.pojo.WutanduixiangZonghecejingFangshexingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WutanduixiangZonghecejingFangshexingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(WutanduixiangZonghecejingFangshexingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(WutanduixiangZonghecejingFangshexingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long wtdxZhcjFsxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(WutanduixiangZonghecejingFangshexing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(WutanduixiangZonghecejingFangshexing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<WutanduixiangZonghecejingFangshexing> selectByExample(WutanduixiangZonghecejingFangshexingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    WutanduixiangZonghecejingFangshexing selectByPrimaryKey(Long wtdxZhcjFsxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") WutanduixiangZonghecejingFangshexing record, @Param("example") WutanduixiangZonghecejingFangshexingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") WutanduixiangZonghecejingFangshexing record, @Param("example") WutanduixiangZonghecejingFangshexingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(WutanduixiangZonghecejingFangshexing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutanduixiang_zonghecejing_fangshexing
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(WutanduixiangZonghecejingFangshexing record);
}