package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.WutanGaomidudianfaBck;
import cn.xjtu.zun.tiesheyuan.pojo.WutanGaomidudianfaBckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WutanGaomidudianfaBckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(WutanGaomidudianfaBckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(WutanGaomidudianfaBckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long wtGmddfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(WutanGaomidudianfaBck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(WutanGaomidudianfaBck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<WutanGaomidudianfaBck> selectByExample(WutanGaomidudianfaBckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    WutanGaomidudianfaBck selectByPrimaryKey(Long wtGmddfid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") WutanGaomidudianfaBck record, @Param("example") WutanGaomidudianfaBckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") WutanGaomidudianfaBck record, @Param("example") WutanGaomidudianfaBckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(WutanGaomidudianfaBck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wutan_gaomidudianfa_bck
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(WutanGaomidudianfaBck record);
}