package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.Zuankong;
import cn.xjtu.zun.tiesheyuan.pojo.ZuankongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZuankongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ZuankongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ZuankongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long zkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(Zuankong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(Zuankong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<Zuankong> selectByExample(ZuankongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    Zuankong selectByPrimaryKey(Long zkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") Zuankong record, @Param("example") ZuankongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") Zuankong record, @Param("example") ZuankongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(Zuankong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankong
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(Zuankong record);
}