package cn.xjtu.zun.tiesheyuan.mapper;

import cn.xjtu.zun.tiesheyuan.pojo.ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi;
import cn.xjtu.zun.tiesheyuan.pojo.ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    long countByExample(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByExample(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int deleteByPrimaryKey(Long zkywcsSwcsCssyglqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insert(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int insertSelective(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    List<ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi> selectByExample(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi selectByPrimaryKey(Long zkywcsSwcsCssyglqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExampleSelective(@Param("record") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi record, @Param("example") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByExample(@Param("record") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi record, @Param("example") ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKeySelective(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zuankongyuanweiceshi_shuiwenceshi_choushuishiyanguolvqi
     *
     * @mbg.generated Wed Aug 02 15:45:26 CST 2023
     */
    int updateByPrimaryKey(ZuankongyuanweiceshiShuiwenceshiChoushuishiyanguolvqi record);
}